apiVersion: functions.oci.upbound.io/v1alpha1
kind: Function
metadata:
  annotations:
    meta.upbound.io/example-id: functions/v1alpha1/function
  labels:
    testing.upbound.io/example-name: test_function
  name: test-function
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_application
    displayName: displayName
    image: ${var.image}
    memoryInMbs: "128"

---

apiVersion: networking.oci.upbound.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: functions/v1alpha1/function
  labels:
    testing.upbound.io/example-name: test_subnet
  name: test-subnet
spec:
  forProvider:
    cidrBlock: 10.0.0.0/24
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_vcn

---

apiVersion: networking.oci.upbound.io/v1alpha1
kind: Vcn
metadata:
  annotations:
    meta.upbound.io/example-id: functions/v1alpha1/function
  labels:
    testing.upbound.io/example-name: test_vcn
  name: test-vcn
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
