apiVersion: networking.oci.upbound.io/v1alpha1
kind: InternetGateway
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/internetgateway
  labels:
    testing.upbound.io/example-name: ig
  name: ig
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    displayName: proxy_prototype
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: this

---

apiVersion: networking.oci.upbound.io/v1alpha1
kind: Vcn
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/internetgateway
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    cidrBlock: ${var.vcn_cidr}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    displayName: proxy_prototype
    dnsLabel: pp
