apiVersion: networking.oci.upbound.io/v1alpha1
kind: NetworkSecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/networksecuritygroup
  labels:
    testing.upbound.io/example-name: test_network_security_group
  name: test-network-security-group
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    displayName: testNetworkSecurityGroup
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_vcn

---

apiVersion: networking.oci.upbound.io/v1alpha1
kind: Vcn
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/networksecuritygroup
  labels:
    testing.upbound.io/example-name: test_vcn
  name: test-vcn
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    displayName: testVcn
    dnsLabel: dnslabel
