apiVersion: networking.oci.upbound.io/v1alpha1
kind: PublicIp
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/publicip
  labels:
    testing.upbound.io/example-name: ephemeral_public_ip_assigned
  name: ephemeral-public-ip-assigned
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    displayName: ephemeralPublicIPAssigned
    lifetime: EPHEMERAL
    privateIpIdSelector:
      matchLabels:
        testing.upbound.io/example-name: oci_core_private_ips
