/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AwrHub) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AwrHubSource) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AwrHubSourceAwrhubsourcesManagement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DatabaseInsight) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EnterpriseManagerBridge) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ExadataInsight) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HostInsight) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NewsReport) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OperationsInsightsPrivateEndpoint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OperationsInsightsWarehouse) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OperationsInsightsWarehouseDownloadWarehouseWallet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OperationsInsightsWarehouseRotateWarehouseWallet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OperationsInsightsWarehouseUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OpsiConfiguration) Hub() {}
