/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CalculateAuditVolumeCollectedInitParameters struct {

	// The OCID of the audit.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/datasafe/v1alpha1.AuditProfile
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	AuditProfileID *string `json:"auditProfileId,omitempty" tf:"audit_profile_id,omitempty"`

	// Reference to a AuditProfile in datasafe to populate auditProfileId.
	// +kubebuilder:validation:Optional
	AuditProfileIDRef *v1.Reference `json:"auditProfileIdRef,omitempty" tf:"-"`

	// Selector for a AuditProfile in datasafe to populate auditProfileId.
	// +kubebuilder:validation:Optional
	AuditProfileIDSelector *v1.Selector `json:"auditProfileIdSelector,omitempty" tf:"-"`

	// The date from which the audit volume collected by data safe has to be calculated, in the format defined by RFC3339.
	TimeFromMonth *string `json:"timeFromMonth,omitempty" tf:"time_from_month,omitempty"`

	// The date from which the audit volume collected by data safe has to be calculated, in the format defined by RFC3339. If not specified, this will default to the current date.
	TimeToMonth *string `json:"timeToMonth,omitempty" tf:"time_to_month,omitempty"`
}

type CalculateAuditVolumeCollectedObservation struct {

	// The OCID of the audit.
	AuditProfileID *string `json:"auditProfileId,omitempty" tf:"audit_profile_id,omitempty"`

	// List of collected audit volumes.
	CollectedAuditVolumes []CollectedAuditVolumesObservation `json:"collectedAuditVolumes,omitempty" tf:"collected_audit_volumes,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The date from which the audit volume collected by data safe has to be calculated, in the format defined by RFC3339.
	TimeFromMonth *string `json:"timeFromMonth,omitempty" tf:"time_from_month,omitempty"`

	// The date from which the audit volume collected by data safe has to be calculated, in the format defined by RFC3339. If not specified, this will default to the current date.
	TimeToMonth *string `json:"timeToMonth,omitempty" tf:"time_to_month,omitempty"`
}

type CalculateAuditVolumeCollectedParameters struct {

	// The OCID of the audit.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/datasafe/v1alpha1.AuditProfile
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	AuditProfileID *string `json:"auditProfileId,omitempty" tf:"audit_profile_id,omitempty"`

	// Reference to a AuditProfile in datasafe to populate auditProfileId.
	// +kubebuilder:validation:Optional
	AuditProfileIDRef *v1.Reference `json:"auditProfileIdRef,omitempty" tf:"-"`

	// Selector for a AuditProfile in datasafe to populate auditProfileId.
	// +kubebuilder:validation:Optional
	AuditProfileIDSelector *v1.Selector `json:"auditProfileIdSelector,omitempty" tf:"-"`

	// The date from which the audit volume collected by data safe has to be calculated, in the format defined by RFC3339.
	// +kubebuilder:validation:Optional
	TimeFromMonth *string `json:"timeFromMonth,omitempty" tf:"time_from_month,omitempty"`

	// The date from which the audit volume collected by data safe has to be calculated, in the format defined by RFC3339. If not specified, this will default to the current date.
	// +kubebuilder:validation:Optional
	TimeToMonth *string `json:"timeToMonth,omitempty" tf:"time_to_month,omitempty"`
}

type CollectedAuditVolumesInitParameters struct {
}

type CollectedAuditVolumesObservation struct {
	ArchivedVolume *string `json:"archivedVolume,omitempty" tf:"archived_volume,omitempty"`

	// The OCID of the audit.
	AuditProfileID *string `json:"auditProfileId,omitempty" tf:"audit_profile_id,omitempty"`

	MonthInConsideration *string `json:"monthInConsideration,omitempty" tf:"month_in_consideration,omitempty"`

	OnlineVolume *string `json:"onlineVolume,omitempty" tf:"online_volume,omitempty"`
}

type CollectedAuditVolumesParameters struct {
}

// CalculateAuditVolumeCollectedSpec defines the desired state of CalculateAuditVolumeCollected
type CalculateAuditVolumeCollectedSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CalculateAuditVolumeCollectedParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CalculateAuditVolumeCollectedInitParameters `json:"initProvider,omitempty"`
}

// CalculateAuditVolumeCollectedStatus defines the observed state of CalculateAuditVolumeCollected.
type CalculateAuditVolumeCollectedStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CalculateAuditVolumeCollectedObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CalculateAuditVolumeCollected is the Schema for the CalculateAuditVolumeCollecteds API. Provides the Calculate Audit Volume Collected resource in Oracle Cloud Infrastructure Data Safe service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type CalculateAuditVolumeCollected struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.timeFromMonth) || (has(self.initProvider) && has(self.initProvider.timeFromMonth))",message="spec.forProvider.timeFromMonth is a required parameter"
	Spec   CalculateAuditVolumeCollectedSpec   `json:"spec"`
	Status CalculateAuditVolumeCollectedStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CalculateAuditVolumeCollectedList contains a list of CalculateAuditVolumeCollecteds
type CalculateAuditVolumeCollectedList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CalculateAuditVolumeCollected `json:"items"`
}

// Repository type metadata.
var (
	CalculateAuditVolumeCollected_Kind             = "CalculateAuditVolumeCollected"
	CalculateAuditVolumeCollected_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CalculateAuditVolumeCollected_Kind}.String()
	CalculateAuditVolumeCollected_KindAPIVersion   = CalculateAuditVolumeCollected_Kind + "." + CRDGroupVersion.String()
	CalculateAuditVolumeCollected_GroupVersionKind = CRDGroupVersion.WithKind(CalculateAuditVolumeCollected_Kind)
)

func init() {
	SchemeBuilder.Register(&CalculateAuditVolumeCollected{}, &CalculateAuditVolumeCollectedList{})
}
