/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BudgetInitParameters struct {

	// (Updatable) The amount of the budget expressed as a whole number in the currency of the customer's rate card.
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (Updatable) The number of days offset from the first day of the month, at which the budget processing period starts. In months that have fewer days than this value, processing will begin on the last day of that month. For example, for a value of 12, processing starts every month on the 12th at midnight.
	BudgetProcessingPeriodStartOffset *float64 `json:"budgetProcessingPeriodStartOffset,omitempty" tf:"budget_processing_period_start_offset,omitempty"`

	// The OCID of the compartment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The description of the budget.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The displayName of the budget. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) The date when the one-time budget concludes. For example, 2023-03-23. The date-time format conforms to RFC 3339, and will be truncated to the starting point of the date provided after being converted to UTC time.
	EndDate *string `json:"endDate,omitempty" tf:"end_date,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) The type of the budget processing period. Valid values are INVOICE, MONTH, and SINGLE_USE.
	ProcessingPeriodType *string `json:"processingPeriodType,omitempty" tf:"processing_period_type,omitempty"`

	// (Updatable) The reset period for the budget. Valid value is MONTHLY.
	ResetPeriod *string `json:"resetPeriod,omitempty" tf:"reset_period,omitempty"`

	// (Updatable) The date when the one-time budget begins. For example, 2023-03-23. The date-time format conforms to RFC 3339, and will be truncated to the starting point of the date provided after being converted to UTC time.
	StartDate *string `json:"startDate,omitempty" tf:"start_date,omitempty"`

	// This is DEPRECATED. Set the target compartment ID in targets instead.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	TargetCompartmentID *string `json:"targetCompartmentId,omitempty" tf:"target_compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate targetCompartmentId.
	// +kubebuilder:validation:Optional
	TargetCompartmentIDRef *v1.NamespacedReference `json:"targetCompartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate targetCompartmentId.
	// +kubebuilder:validation:Optional
	TargetCompartmentIDSelector *v1.NamespacedSelector `json:"targetCompartmentIdSelector,omitempty" tf:"-"`

	// The type of target on which the budget is applied.
	TargetType *string `json:"targetType,omitempty" tf:"target_type,omitempty"`

	// The list of targets on which the budget is applied. If targetType is "COMPARTMENT", the targets contain the list of compartment OCIDs. If targetType is "TAG", the targets contain the list of cost tracking tag identifiers in the form of "{tagNamespace}.{tagKey}.{tagValue}". Curerntly, the array should contain exactly one item.
	Targets []*string `json:"targets,omitempty" tf:"targets,omitempty"`
}

type BudgetObservation struct {

	// The actual spend in currency for the current budget cycle.
	ActualSpend *float64 `json:"actualSpend,omitempty" tf:"actual_spend,omitempty"`

	// The total number of alert rules in the budget.
	AlertRuleCount *float64 `json:"alertRuleCount,omitempty" tf:"alert_rule_count,omitempty"`

	// (Updatable) The amount of the budget expressed as a whole number in the currency of the customer's rate card.
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (Updatable) The number of days offset from the first day of the month, at which the budget processing period starts. In months that have fewer days than this value, processing will begin on the last day of that month. For example, for a value of 12, processing starts every month on the 12th at midnight.
	BudgetProcessingPeriodStartOffset *float64 `json:"budgetProcessingPeriodStartOffset,omitempty" tf:"budget_processing_period_start_offset,omitempty"`

	// The OCID of the compartment.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The description of the budget.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The displayName of the budget. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) The date when the one-time budget concludes. For example, 2023-03-23. The date-time format conforms to RFC 3339, and will be truncated to the starting point of the date provided after being converted to UTC time.
	EndDate *string `json:"endDate,omitempty" tf:"end_date,omitempty"`

	// The forecasted spend in currency by the end of the current budget cycle.
	ForecastedSpend *float64 `json:"forecastedSpend,omitempty" tf:"forecasted_spend,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the budget.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) The type of the budget processing period. Valid values are INVOICE, MONTH, and SINGLE_USE.
	ProcessingPeriodType *string `json:"processingPeriodType,omitempty" tf:"processing_period_type,omitempty"`

	// (Updatable) The reset period for the budget. Valid value is MONTHLY.
	ResetPeriod *string `json:"resetPeriod,omitempty" tf:"reset_period,omitempty"`

	// (Updatable) The date when the one-time budget begins. For example, 2023-03-23. The date-time format conforms to RFC 3339, and will be truncated to the starting point of the date provided after being converted to UTC time.
	StartDate *string `json:"startDate,omitempty" tf:"start_date,omitempty"`

	// The current state of the budget.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// This is DEPRECATED. Set the target compartment ID in targets instead.
	TargetCompartmentID *string `json:"targetCompartmentId,omitempty" tf:"target_compartment_id,omitempty"`

	// The type of target on which the budget is applied.
	TargetType *string `json:"targetType,omitempty" tf:"target_type,omitempty"`

	// The list of targets on which the budget is applied. If targetType is "COMPARTMENT", the targets contain the list of compartment OCIDs. If targetType is "TAG", the targets contain the list of cost tracking tag identifiers in the form of "{tagNamespace}.{tagKey}.{tagValue}". Curerntly, the array should contain exactly one item.
	Targets []*string `json:"targets,omitempty" tf:"targets,omitempty"`

	// The time that the budget was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The time that the budget spend was last computed.
	TimeSpendComputed *string `json:"timeSpendComputed,omitempty" tf:"time_spend_computed,omitempty"`

	// The time that the budget was updated.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// The version of the budget. Starts from 1 and increments by 1.
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type BudgetParameters struct {

	// (Updatable) The amount of the budget expressed as a whole number in the currency of the customer's rate card.
	// +kubebuilder:validation:Optional
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (Updatable) The number of days offset from the first day of the month, at which the budget processing period starts. In months that have fewer days than this value, processing will begin on the last day of that month. For example, for a value of 12, processing starts every month on the 12th at midnight.
	// +kubebuilder:validation:Optional
	BudgetProcessingPeriodStartOffset *float64 `json:"budgetProcessingPeriodStartOffset,omitempty" tf:"budget_processing_period_start_offset,omitempty"`

	// The OCID of the compartment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The description of the budget.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The displayName of the budget. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) The date when the one-time budget concludes. For example, 2023-03-23. The date-time format conforms to RFC 3339, and will be truncated to the starting point of the date provided after being converted to UTC time.
	// +kubebuilder:validation:Optional
	EndDate *string `json:"endDate,omitempty" tf:"end_date,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) The type of the budget processing period. Valid values are INVOICE, MONTH, and SINGLE_USE.
	// +kubebuilder:validation:Optional
	ProcessingPeriodType *string `json:"processingPeriodType,omitempty" tf:"processing_period_type,omitempty"`

	// (Updatable) The reset period for the budget. Valid value is MONTHLY.
	// +kubebuilder:validation:Optional
	ResetPeriod *string `json:"resetPeriod,omitempty" tf:"reset_period,omitempty"`

	// (Updatable) The date when the one-time budget begins. For example, 2023-03-23. The date-time format conforms to RFC 3339, and will be truncated to the starting point of the date provided after being converted to UTC time.
	// +kubebuilder:validation:Optional
	StartDate *string `json:"startDate,omitempty" tf:"start_date,omitempty"`

	// This is DEPRECATED. Set the target compartment ID in targets instead.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	TargetCompartmentID *string `json:"targetCompartmentId,omitempty" tf:"target_compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate targetCompartmentId.
	// +kubebuilder:validation:Optional
	TargetCompartmentIDRef *v1.NamespacedReference `json:"targetCompartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate targetCompartmentId.
	// +kubebuilder:validation:Optional
	TargetCompartmentIDSelector *v1.NamespacedSelector `json:"targetCompartmentIdSelector,omitempty" tf:"-"`

	// The type of target on which the budget is applied.
	// +kubebuilder:validation:Optional
	TargetType *string `json:"targetType,omitempty" tf:"target_type,omitempty"`

	// The list of targets on which the budget is applied. If targetType is "COMPARTMENT", the targets contain the list of compartment OCIDs. If targetType is "TAG", the targets contain the list of cost tracking tag identifiers in the form of "{tagNamespace}.{tagKey}.{tagValue}". Curerntly, the array should contain exactly one item.
	// +kubebuilder:validation:Optional
	Targets []*string `json:"targets,omitempty" tf:"targets,omitempty"`
}

// BudgetSpec defines the desired state of Budget
type BudgetSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BudgetParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BudgetInitParameters `json:"initProvider,omitempty"`
}

// BudgetStatus defines the observed state of Budget.
type BudgetStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BudgetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Budget is the Schema for the Budgets API. Provides the Budget resource in Oracle Cloud Infrastructure Budget service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type Budget struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.amount) || (has(self.initProvider) && has(self.initProvider.amount))",message="spec.forProvider.amount is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resetPeriod) || (has(self.initProvider) && has(self.initProvider.resetPeriod))",message="spec.forProvider.resetPeriod is a required parameter"
	Spec   BudgetSpec   `json:"spec"`
	Status BudgetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BudgetList contains a list of Budgets
type BudgetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Budget `json:"items"`
}

// Repository type metadata.
var (
	Budget_Kind             = "Budget"
	Budget_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Budget_Kind}.String()
	Budget_KindAPIVersion   = Budget_Kind + "." + CRDGroupVersion.String()
	Budget_GroupVersionKind = CRDGroupVersion.WithKind(Budget_Kind)
)

func init() {
	SchemeBuilder.Register(&Budget{}, &BudgetList{})
}
