/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AutonomousContainerDatabaseAddStandbyBackupConfigInitParameters struct {
}

type AutonomousContainerDatabaseAddStandbyBackupConfigObservation struct {

	// Backup destination details.
	BackupDestinationDetails []BackupConfigBackupDestinationDetailsObservation `json:"backupDestinationDetails,omitempty" tf:"backup_destination_details,omitempty"`

	// Number of days between the current and the earliest point of recoverability covered by automatic backups. This value applies to automatic backups. After a new automatic backup has been created, Oracle removes old automatic backups that are created before the window. When the value is updated, it is applied to all existing automatic backups. If the number of specified days is 0 then there will be no backups.
	RecoveryWindowInDays *float64 `json:"recoveryWindowInDays,omitempty" tf:"recovery_window_in_days,omitempty"`
}

type AutonomousContainerDatabaseAddStandbyBackupConfigParameters struct {
}

type AutonomousContainerDatabaseAddStandbyDataguardGroupMembersInitParameters struct {
}

type AutonomousContainerDatabaseAddStandbyDataguardGroupMembersObservation struct {

	// The lag time between updates to the primary Autonomous Container Database and application of the redo data on the standby Autonomous Container Database, as computed by the reporting database. Example: 9 seconds
	ApplyLag *string `json:"applyLag,omitempty" tf:"apply_lag,omitempty"`

	// The rate at which redo logs are synchronized between the associated Autonomous Container Databases. Example: 180 Mb per second
	ApplyRate *string `json:"applyRate,omitempty" tf:"apply_rate,omitempty"`

	// Automatically selected by backend when observer is enabled.
	AutomaticFailoverTarget *string `json:"automaticFailoverTarget,omitempty" tf:"automatic_failover_target,omitempty"`

	// The Autonomous Container Database OCID.
	AutonomousContainerDatabaseID *string `json:"autonomousContainerDatabaseId,omitempty" tf:"autonomous_container_database_id,omitempty"`

	// The availability domain of the Autonomous Container Database.
	AvailabilityDomain *string `json:"availabilityDomain,omitempty" tf:"availability_domain,omitempty"`

	// The lag time for my preference based on data loss tolerance in seconds.
	FastStartFailOverLagLimitInSeconds *float64 `json:"fastStartFailOverLagLimitInSeconds,omitempty" tf:"fast_start_fail_over_lag_limit_in_seconds,omitempty"`

	// Indicates whether Automatic Failover is enabled for Autonomous Container Database Dataguard Association
	IsAutomaticFailoverEnabled *bool `json:"isAutomaticFailoverEnabled,omitempty" tf:"is_automatic_failover_enabled,omitempty"`

	// Additional information about the current lifecycleState, if available.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// The protection mode of this Autonomous Data Guard association. For more information, see Oracle Data Guard Protection Modes in the Oracle Data Guard documentation.
	ProtectionMode *string `json:"protectionMode,omitempty" tf:"protection_mode,omitempty"`

	// Automatically selected by backend based on the protection mode.
	RedoTransportMode *string `json:"redoTransportMode,omitempty" tf:"redo_transport_mode,omitempty"`

	// The Data Guard role of the Autonomous Container Database or Autonomous AI Database, if Autonomous Data Guard is enabled.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// The current state of Autonomous Data Guard.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The date and time the Autonomous DataGuard association was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// Timestamp when the lags were last calculated for a standby.
	TimeLagRefreshedOn *string `json:"timeLagRefreshedOn,omitempty" tf:"time_lag_refreshed_on,omitempty"`

	// The date and time when the last role change action happened.
	TimeLastRoleChanged *string `json:"timeLastRoleChanged,omitempty" tf:"time_last_role_changed,omitempty"`

	// The date and time of the last update to the apply lag, apply rate, and transport lag values.
	TimeLastSynced *string `json:"timeLastSynced,omitempty" tf:"time_last_synced,omitempty"`

	// The approximate number of seconds of redo data not yet available on the standby Autonomous Container Database, as computed by the reporting database. Example: 7 seconds
	TransportLag *string `json:"transportLag,omitempty" tf:"transport_lag,omitempty"`
}

type AutonomousContainerDatabaseAddStandbyDataguardGroupMembersParameters struct {
}

type AutonomousContainerDatabaseAddStandbyDataguardInitParameters struct {
}

type AutonomousContainerDatabaseAddStandbyDataguardObservation struct {

	// The lag time between updates to the primary Autonomous Container Database and application of the redo data on the standby Autonomous Container Database, as computed by the reporting database. Example: 9 seconds
	ApplyLag *string `json:"applyLag,omitempty" tf:"apply_lag,omitempty"`

	// The rate at which redo logs are synchronized between the associated Autonomous Container Databases. Example: 180 Mb per second
	ApplyRate *string `json:"applyRate,omitempty" tf:"apply_rate,omitempty"`

	// Automatically selected by backend when observer is enabled.
	AutomaticFailoverTarget *string `json:"automaticFailoverTarget,omitempty" tf:"automatic_failover_target,omitempty"`

	// The Autonomous Container Database OCID.
	AutonomousContainerDatabaseID *string `json:"autonomousContainerDatabaseId,omitempty" tf:"autonomous_container_database_id,omitempty"`

	// The availability domain of the Autonomous Container Database.
	AvailabilityDomain *string `json:"availabilityDomain,omitempty" tf:"availability_domain,omitempty"`

	// The lag time for my preference based on data loss tolerance in seconds.
	FastStartFailOverLagLimitInSeconds *float64 `json:"fastStartFailOverLagLimitInSeconds,omitempty" tf:"fast_start_fail_over_lag_limit_in_seconds,omitempty"`

	// Indicates whether Automatic Failover is enabled for Autonomous Container Database Dataguard Association
	IsAutomaticFailoverEnabled *bool `json:"isAutomaticFailoverEnabled,omitempty" tf:"is_automatic_failover_enabled,omitempty"`

	// Additional information about the current lifecycleState, if available.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// The protection mode of this Autonomous Data Guard association. For more information, see Oracle Data Guard Protection Modes in the Oracle Data Guard documentation.
	ProtectionMode *string `json:"protectionMode,omitempty" tf:"protection_mode,omitempty"`

	// Automatically selected by backend based on the protection mode.
	RedoTransportMode *string `json:"redoTransportMode,omitempty" tf:"redo_transport_mode,omitempty"`

	// The Data Guard role of the Autonomous Container Database or Autonomous AI Database, if Autonomous Data Guard is enabled.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// The current state of Autonomous Data Guard.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The date and time the Autonomous DataGuard association was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// Timestamp when the lags were last calculated for a standby.
	TimeLagRefreshedOn *string `json:"timeLagRefreshedOn,omitempty" tf:"time_lag_refreshed_on,omitempty"`

	// The date and time when the last role change action happened.
	TimeLastRoleChanged *string `json:"timeLastRoleChanged,omitempty" tf:"time_last_role_changed,omitempty"`

	// The date and time of the last update to the apply lag, apply rate, and transport lag values.
	TimeLastSynced *string `json:"timeLastSynced,omitempty" tf:"time_last_synced,omitempty"`

	// The approximate number of seconds of redo data not yet available on the standby Autonomous Container Database, as computed by the reporting database. Example: 7 seconds
	TransportLag *string `json:"transportLag,omitempty" tf:"transport_lag,omitempty"`
}

type AutonomousContainerDatabaseAddStandbyDataguardParameters struct {
}

type AutonomousContainerDatabaseAddStandbyInitParameters struct {

	// The Autonomous Container Database OCID.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/database/v1alpha1.AutonomousContainerDatabase
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	AutonomousContainerDatabaseID *string `json:"autonomousContainerDatabaseId,omitempty" tf:"autonomous_container_database_id,omitempty"`

	// Reference to a AutonomousContainerDatabase in database to populate autonomousContainerDatabaseId.
	// +kubebuilder:validation:Optional
	AutonomousContainerDatabaseIDRef *v1.Reference `json:"autonomousContainerDatabaseIdRef,omitempty" tf:"-"`

	// Selector for a AutonomousContainerDatabase in database to populate autonomousContainerDatabaseId.
	// +kubebuilder:validation:Optional
	AutonomousContainerDatabaseIDSelector *v1.Selector `json:"autonomousContainerDatabaseIdSelector,omitempty" tf:"-"`

	// The lag time for my preference based on data loss tolerance in seconds.
	FastStartFailOverLagLimitInSeconds *float64 `json:"fastStartFailOverLagLimitInSeconds,omitempty" tf:"fast_start_fail_over_lag_limit_in_seconds,omitempty"`

	// Indicates whether Automatic Failover is enabled for Autonomous Container Database Dataguard Association
	IsAutomaticFailoverEnabled *bool `json:"isAutomaticFailoverEnabled,omitempty" tf:"is_automatic_failover_enabled,omitempty"`

	// Backup options for the standby Autonomous Container Database.
	PeerAutonomousContainerDatabaseBackupConfig []AutonomousContainerDatabaseAddStandbyPeerAutonomousContainerDatabaseBackupConfigInitParameters `json:"peerAutonomousContainerDatabaseBackupConfig,omitempty" tf:"peer_autonomous_container_database_backup_config,omitempty"`

	// The OCID of the compartment where the standby Autonomous Container Database will be created.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/identity/v1alpha1.Compartment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	PeerAutonomousContainerDatabaseCompartmentID *string `json:"peerAutonomousContainerDatabaseCompartmentId,omitempty" tf:"peer_autonomous_container_database_compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate peerAutonomousContainerDatabaseCompartmentId.
	// +kubebuilder:validation:Optional
	PeerAutonomousContainerDatabaseCompartmentIDRef *v1.Reference `json:"peerAutonomousContainerDatabaseCompartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate peerAutonomousContainerDatabaseCompartmentId.
	// +kubebuilder:validation:Optional
	PeerAutonomousContainerDatabaseCompartmentIDSelector *v1.Selector `json:"peerAutonomousContainerDatabaseCompartmentIdSelector,omitempty" tf:"-"`

	// The display name for the peer Autonomous Container Database.
	PeerAutonomousContainerDatabaseDisplayName *string `json:"peerAutonomousContainerDatabaseDisplayName,omitempty" tf:"peer_autonomous_container_database_display_name,omitempty"`

	// The OCID of the peer Autonomous Exadata VM Cluster.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/database/v1alpha1.AutonomousVmCluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	PeerAutonomousVMClusterID *string `json:"peerAutonomousVmClusterId,omitempty" tf:"peer_autonomous_vm_cluster_id,omitempty"`

	// Reference to a AutonomousVmCluster in database to populate peerAutonomousVmClusterId.
	// +kubebuilder:validation:Optional
	PeerAutonomousVMClusterIDRef *v1.Reference `json:"peerAutonomousVmClusterIdRef,omitempty" tf:"-"`

	// Selector for a AutonomousVmCluster in database to populate peerAutonomousVmClusterId.
	// +kubebuilder:validation:Optional
	PeerAutonomousVMClusterIDSelector *v1.Selector `json:"peerAutonomousVmClusterIdSelector,omitempty" tf:"-"`

	// The OCID of the peer cloud Autonomous Exadata VM Cluster.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/database/v1alpha1.CloudAutonomousVmCluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	PeerCloudAutonomousVMClusterID *string `json:"peerCloudAutonomousVmClusterId,omitempty" tf:"peer_cloud_autonomous_vm_cluster_id,omitempty"`

	// Reference to a CloudAutonomousVmCluster in database to populate peerCloudAutonomousVmClusterId.
	// +kubebuilder:validation:Optional
	PeerCloudAutonomousVMClusterIDRef *v1.Reference `json:"peerCloudAutonomousVmClusterIdRef,omitempty" tf:"-"`

	// Selector for a CloudAutonomousVmCluster in database to populate peerCloudAutonomousVmClusterId.
	// +kubebuilder:validation:Optional
	PeerCloudAutonomousVMClusterIDSelector *v1.Selector `json:"peerCloudAutonomousVmClusterIdSelector,omitempty" tf:"-"`

	// Specifies the DB_UNIQUE_NAME of the peer database to be created.
	PeerDBUniqueName *string `json:"peerDbUniqueName,omitempty" tf:"peer_db_unique_name,omitempty"`

	// The protection mode of this Autonomous Data Guard association. For more information, see Oracle Data Guard Protection Modes in the Oracle Data Guard documentation.
	ProtectionMode *string `json:"protectionMode,omitempty" tf:"protection_mode,omitempty"`

	// The scheduling detail for the quarterly maintenance window of the standby Autonomous Container Database. This value represents the number of days before scheduled maintenance of the primary database.
	StandbyMaintenanceBufferInDays *float64 `json:"standbyMaintenanceBufferInDays,omitempty" tf:"standby_maintenance_buffer_in_days,omitempty"`
}

type AutonomousContainerDatabaseAddStandbyKeyHistoryEntryInitParameters struct {
}

type AutonomousContainerDatabaseAddStandbyKeyHistoryEntryObservation struct {

	// The OCID of the backup destination.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the key container version that is used in database transparent data encryption (TDE) operations KMS Key can have multiple key versions. If none is specified, the current key version (latest) of the Key Id is used for the operation. Autonomous AI Database Serverless does not use key versions, hence is not applicable for Autonomous AI Database Serverless instances.
	KMSKeyVersionID *string `json:"kmsKeyVersionId,omitempty" tf:"kms_key_version_id,omitempty"`

	// The date and time the kms key activated.
	TimeActivated *string `json:"timeActivated,omitempty" tf:"time_activated,omitempty"`

	// The OCID of the Oracle Cloud Infrastructure vault. This parameter and secretId are required for Customer Managed Keys.
	VaultID *string `json:"vaultId,omitempty" tf:"vault_id,omitempty"`
}

type AutonomousContainerDatabaseAddStandbyKeyHistoryEntryParameters struct {
}

type AutonomousContainerDatabaseAddStandbyMaintenanceWindowInitParameters struct {
}

type AutonomousContainerDatabaseAddStandbyMaintenanceWindowObservation struct {

	// Determines the amount of time the system will wait before the start of each database server patching operation. Custom action timeout is in minutes and valid value is between 15 to 120 (inclusive).
	CustomActionTimeoutInMins *float64 `json:"customActionTimeoutInMins,omitempty" tf:"custom_action_timeout_in_mins,omitempty"`

	// Days during the week when maintenance should be performed.
	DaysOfWeek []MaintenanceWindowDaysOfWeekObservation `json:"daysOfWeek,omitempty" tf:"days_of_week,omitempty"`

	// The window of hours during the day when maintenance should be performed. The window is a 4 hour slot. Valid values are - 0 - represents time slot 0:00 - 3:59 UTC - 4 - represents time slot 4:00 - 7:59 UTC - 8 - represents time slot 8:00 - 11:59 UTC - 12 - represents time slot 12:00 - 15:59 UTC - 16 - represents time slot 16:00 - 19:59 UTC - 20 - represents time slot 20:00 - 23:59 UTC
	HoursOfDay []*float64 `json:"hoursOfDay,omitempty" tf:"hours_of_day,omitempty"`

	// If true, enables the configuration of a custom action timeout (waiting period) between database server patching operations.
	IsCustomActionTimeoutEnabled *bool `json:"isCustomActionTimeoutEnabled,omitempty" tf:"is_custom_action_timeout_enabled,omitempty"`

	// If true, enables the monthly patching option.
	IsMonthlyPatchingEnabled *bool `json:"isMonthlyPatchingEnabled,omitempty" tf:"is_monthly_patching_enabled,omitempty"`

	// Lead time window allows user to set a lead time to prepare for a down time. The lead time is in weeks and valid value is between 1 to 4.
	LeadTimeInWeeks *float64 `json:"leadTimeInWeeks,omitempty" tf:"lead_time_in_weeks,omitempty"`

	// Months during the year when maintenance should be performed.
	Months []MaintenanceWindowMonthsObservation `json:"months,omitempty" tf:"months,omitempty"`

	// Cloud Exadata infrastructure node patching method, either "ROLLING" or "NONROLLING". Default value is ROLLING.
	PatchingMode *string `json:"patchingMode,omitempty" tf:"patching_mode,omitempty"`

	// The maintenance window scheduling preference.
	Preference *string `json:"preference,omitempty" tf:"preference,omitempty"`

	// If true, skips the release update (RU) for the quarter. You cannot skip two consecutive quarters. An RU skip request will only be honoured if the current version of the Autonomous Container Database is supported for current quarter.
	SkipRu []*bool `json:"skipRu,omitempty" tf:"skip_ru,omitempty"`

	// Weeks during the month when maintenance should be performed. Weeks start on the 1st, 8th, 15th, and 22nd days of the month, and have a duration of 7 days. Weeks start and end based on calendar dates, not days of the week. For example, to allow maintenance during the 2nd week of the month (from the 8th day to the 14th day of the month), use the value 2. Maintenance cannot be scheduled for the fifth week of months that contain more than 28 days. Note that this parameter works in conjunction with the  daysOfWeek and hoursOfDay parameters to allow you to specify specific days of the week and hours that maintenance will be performed.
	WeeksOfMonth []*float64 `json:"weeksOfMonth,omitempty" tf:"weeks_of_month,omitempty"`
}

type AutonomousContainerDatabaseAddStandbyMaintenanceWindowParameters struct {
}

type AutonomousContainerDatabaseAddStandbyObservation struct {

	// The Autonomous Container Database OCID.
	AutonomousContainerDatabaseID *string `json:"autonomousContainerDatabaseId,omitempty" tf:"autonomous_container_database_id,omitempty"`

	// No longer used. For Autonomous AI Database on dedicated Exadata infrastructure, the container database is created within a specified cloudAutonomousVmCluster.
	AutonomousExadataInfrastructureID *string `json:"autonomousExadataInfrastructureId,omitempty" tf:"autonomous_exadata_infrastructure_id,omitempty"`

	// The OCID of the Autonomous VM Cluster.
	AutonomousVMClusterID *string `json:"autonomousVmClusterId,omitempty" tf:"autonomous_vm_cluster_id,omitempty"`

	// The availability domain of the Autonomous Container Database.
	AvailabilityDomain *string `json:"availabilityDomain,omitempty" tf:"availability_domain,omitempty"`

	// Sum of CPUs available on the Autonomous VM Cluster + Sum of reclaimable CPUs available in the Autonomous Container Database.
	AvailableCpus *float64 `json:"availableCpus,omitempty" tf:"available_cpus,omitempty"`

	// Backup options for the Autonomous Container Database.
	BackupConfig []AutonomousContainerDatabaseAddStandbyBackupConfigObservation `json:"backupConfig,omitempty" tf:"backup_config,omitempty"`

	// The OCID of the cloud Autonomous Exadata VM Cluster.
	CloudAutonomousVMClusterID *string `json:"cloudAutonomousVmClusterId,omitempty" tf:"cloud_autonomous_vm_cluster_id,omitempty"`

	// The OCID of the compartment.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// The compute model of the Autonomous Container Database. For Autonomous AI Database on Dedicated Exadata Infrastructure, the CPU type (ECPUs or OCPUs) is determined by the parent Autonomous Exadata VM Cluster's compute model. ECPU compute model is the recommended model and OCPU compute model is legacy. See Compute Models in Autonomous AI Database on Dedicated Exadata Infrastructure for more details.
	ComputeModel *string `json:"computeModel,omitempty" tf:"compute_model,omitempty"`

	// The Database name for the Autonomous Container Database. The name must be unique within the Cloud Autonomous VM Cluster, starting with an alphabetic character, followed by 1 to 7 alphanumeric characters.
	DBName *string `json:"dbName,omitempty" tf:"db_name,omitempty"`

	// The CPU value beyond which an Autonomous AI Database will be opened across multiple nodes. The default value of this attribute is 16 for OCPUs and 64 for ECPUs.
	DBSplitThreshold *float64 `json:"dbSplitThreshold,omitempty" tf:"db_split_threshold,omitempty"`

	// Deprecated. The DB_UNIQUE_NAME value is set by Oracle Cloud Infrastructure.  Do not specify a value for this parameter.
	DBUniqueName *string `json:"dbUniqueName,omitempty" tf:"db_unique_name,omitempty"`

	// Oracle AI Database version of the Autonomous Container Database.
	DBVersion *string `json:"dbVersion,omitempty" tf:"db_version,omitempty"`

	// The properties that define Autonomous Container Databases Dataguard.
	Dataguard []AutonomousContainerDatabaseAddStandbyDataguardObservation `json:"dataguard,omitempty" tf:"dataguard,omitempty"`

	// Array of Dg associations.
	DataguardGroupMembers []AutonomousContainerDatabaseAddStandbyDataguardGroupMembersObservation `json:"dataguardGroupMembers,omitempty" tf:"dataguard_group_members,omitempty"`

	// Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// The user-provided name for the Autonomous Container Database.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Determines whether an Autonomous AI Database must be opened across the maximum number of nodes or the least number of nodes. By default, Minimum nodes is selected.
	DistributionAffinity *string `json:"distributionAffinity,omitempty" tf:"distribution_affinity,omitempty"`

	// DST Time-Zone File version of the Autonomous Container Database.
	DstFileVersion *string `json:"dstFileVersion,omitempty" tf:"dst_file_version,omitempty"`

	// The lag time for my preference based on data loss tolerance in seconds.
	FastStartFailOverLagLimitInSeconds *float64 `json:"fastStartFailOverLagLimitInSeconds,omitempty" tf:"fast_start_fail_over_lag_limit_in_seconds,omitempty"`

	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the backup destination.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The infrastructure type this resource belongs to.
	InfrastructureType *string `json:"infrastructureType,omitempty" tf:"infrastructure_type,omitempty"`

	// Indicates whether Automatic Failover is enabled for Autonomous Container Database Dataguard Association
	IsAutomaticFailoverEnabled *bool `json:"isAutomaticFailoverEnabled,omitempty" tf:"is_automatic_failover_enabled,omitempty"`

	// Deprecated. Indicates whether the Autonomous AI Database has local (in-region) Data Guard enabled. Not applicable to cross-region Autonomous Data Guard associations, or to Autonomous AI Databases using dedicated Exadata infrastructure or Exadata Cloud@Customer infrastructure.
	IsDataGuardEnabled *bool `json:"isDataGuardEnabled,omitempty" tf:"is_data_guard_enabled,omitempty"`

	// Indicates if an automatic DST Time Zone file update is enabled for the Autonomous Container Database. If enabled along with Release Update, patching will be done in a Non-Rolling manner.
	IsDstFileUpdateEnabled *bool `json:"isDstFileUpdateEnabled,omitempty" tf:"is_dst_file_update_enabled,omitempty"`

	// Indicates if it is multiple standby Autonomous Dataguard
	IsMultipleStandby *bool `json:"isMultipleStandby,omitempty" tf:"is_multiple_standby,omitempty"`

	// The OCID of the key container that is used as the master encryption key in database transparent data encryption (TDE) operations.
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`

	// The OCID of the key container version that is used in database transparent data encryption (TDE) operations KMS Key can have multiple key versions. If none is specified, the current key version (latest) of the Key Id is used for the operation. Autonomous AI Database Serverless does not use key versions, hence is not applicable for Autonomous AI Database Serverless instances.
	KMSKeyVersionID *string `json:"kmsKeyVersionId,omitempty" tf:"kms_key_version_id,omitempty"`

	// Key History Entry.
	KeyHistoryEntry []AutonomousContainerDatabaseAddStandbyKeyHistoryEntryObservation `json:"keyHistoryEntry,omitempty" tf:"key_history_entry,omitempty"`

	// The OCID of the key store of Oracle Vault.
	KeyStoreID *string `json:"keyStoreId,omitempty" tf:"key_store_id,omitempty"`

	// The wallet name for Oracle Key Vault.
	KeyStoreWalletName *string `json:"keyStoreWalletName,omitempty" tf:"key_store_wallet_name,omitempty"`

	// The largest Autonomous AI Database (CPU) that can be created in a new Autonomous Container Database.
	LargestProvisionableAutonomousDatabaseInCpus *float64 `json:"largestProvisionableAutonomousDatabaseInCpus,omitempty" tf:"largest_provisionable_autonomous_database_in_cpus,omitempty"`

	// The OCID of the last maintenance run.
	LastMaintenanceRunID *string `json:"lastMaintenanceRunId,omitempty" tf:"last_maintenance_run_id,omitempty"`

	// Additional information about the current lifecycleState, if available.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// List of One-Off patches that has been successfully applied to Autonomous Container Database
	ListOneOffPatches []*string `json:"listOneOffPatches,omitempty" tf:"list_one_off_patches,omitempty"`

	// The scheduling details for the quarterly maintenance window. Patching and system updates take place during the maintenance window.
	MaintenanceWindow []AutonomousContainerDatabaseAddStandbyMaintenanceWindowObservation `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// The amount of memory (in GBs) to be enabled per OCPU or ECPU.
	MemoryPerComputeUnitInGbs *float64 `json:"memoryPerComputeUnitInGbs,omitempty" tf:"memory_per_compute_unit_in_gbs,omitempty"`

	// The amount of memory (in GBs, rounded off to nearest integer value) enabled per ECPU or OCPU in the Autonomous VM Cluster. This is deprecated. Please refer to memoryPerComputeUnitInGBs for accurate value.
	MemoryPerOracleComputeUnitInGbs *float64 `json:"memoryPerOracleComputeUnitInGbs,omitempty" tf:"memory_per_oracle_compute_unit_in_gbs,omitempty"`

	// Enabling SHARED server architecture enables a database server to allow many client processes to share very few server processes, thereby increasing the number of supported users.
	NetServicesArchitecture *string `json:"netServicesArchitecture,omitempty" tf:"net_services_architecture,omitempty"`

	// The OCID of the next maintenance run.
	NextMaintenanceRunID *string `json:"nextMaintenanceRunId,omitempty" tf:"next_maintenance_run_id,omitempty"`

	// The OKV End Point Group name for the Autonomous Container Database.
	OkvEndPointGroupName *string `json:"okvEndPointGroupName,omitempty" tf:"okv_end_point_group_name,omitempty"`

	// The OCID of the last patch applied on the system.
	PatchID *string `json:"patchId,omitempty" tf:"patch_id,omitempty"`

	// Database patch model preference.
	PatchModel *string `json:"patchModel,omitempty" tf:"patch_model,omitempty"`

	// Backup options for the standby Autonomous Container Database.
	PeerAutonomousContainerDatabaseBackupConfig []AutonomousContainerDatabaseAddStandbyPeerAutonomousContainerDatabaseBackupConfigObservation `json:"peerAutonomousContainerDatabaseBackupConfig,omitempty" tf:"peer_autonomous_container_database_backup_config,omitempty"`

	// The OCID of the compartment where the standby Autonomous Container Database will be created.
	PeerAutonomousContainerDatabaseCompartmentID *string `json:"peerAutonomousContainerDatabaseCompartmentId,omitempty" tf:"peer_autonomous_container_database_compartment_id,omitempty"`

	// The display name for the peer Autonomous Container Database.
	PeerAutonomousContainerDatabaseDisplayName *string `json:"peerAutonomousContainerDatabaseDisplayName,omitempty" tf:"peer_autonomous_container_database_display_name,omitempty"`

	// The OCID of the peer Autonomous Exadata VM Cluster.
	PeerAutonomousVMClusterID *string `json:"peerAutonomousVmClusterId,omitempty" tf:"peer_autonomous_vm_cluster_id,omitempty"`

	// The OCID of the peer cloud Autonomous Exadata VM Cluster.
	PeerCloudAutonomousVMClusterID *string `json:"peerCloudAutonomousVmClusterId,omitempty" tf:"peer_cloud_autonomous_vm_cluster_id,omitempty"`

	// Specifies the DB_UNIQUE_NAME of the peer database to be created.
	PeerDBUniqueName *string `json:"peerDbUniqueName,omitempty" tf:"peer_db_unique_name,omitempty"`

	// The protection mode of this Autonomous Data Guard association. For more information, see Oracle Data Guard Protection Modes in the Oracle Data Guard documentation.
	ProtectionMode *string `json:"protectionMode,omitempty" tf:"protection_mode,omitempty"`

	// An array of CPU values that can be used to successfully provision a single Autonomous AI Database.
	ProvisionableCpus []*float64 `json:"provisionableCpus,omitempty" tf:"provisionable_cpus,omitempty"`

	// The number of CPUs provisioned in an Autonomous Container Database.
	ProvisionedCpus *float64 `json:"provisionedCpus,omitempty" tf:"provisioned_cpus,omitempty"`

	// CPUs that continue to be included in the count of CPUs available to the Autonomous Container Database even after one of its Autonomous AI Database is terminated or scaled down. You can release them to the available CPUs at its parent Autonomous VM Cluster level by restarting the Autonomous Container Database.
	ReclaimableCpus *float64 `json:"reclaimableCpus,omitempty" tf:"reclaimable_cpus,omitempty"`

	// The number of CPUs reserved in an Autonomous Container Database.
	ReservedCpus *float64 `json:"reservedCpus,omitempty" tf:"reserved_cpus,omitempty"`

	// The Data Guard role of the Autonomous Container Database or Autonomous AI Database, if Autonomous Data Guard is enabled.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// The service level agreement type of the container database. The default is STANDARD.
	ServiceLevelAgreementType *string `json:"serviceLevelAgreementType,omitempty" tf:"service_level_agreement_type,omitempty"`

	// The scheduling detail for the quarterly maintenance window of the standby Autonomous Container Database. This value represents the number of days before scheduled maintenance of the primary database.
	StandbyMaintenanceBufferInDays *float64 `json:"standbyMaintenanceBufferInDays,omitempty" tf:"standby_maintenance_buffer_in_days,omitempty"`

	// The current state of Autonomous Data Guard.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The date and time the Autonomous DataGuard association was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The timestamp of last successful backup. Here NULL value represents either there are no successful backups or backups are not configured for this Autonomous Container Database.
	TimeOfLastBackup *string `json:"timeOfLastBackup,omitempty" tf:"time_of_last_backup,omitempty"`

	// The date and time the Autonomous Container Database will be reverted to Standby from Snapshot Standby.
	TimeSnapshotStandbyRevert *string `json:"timeSnapshotStandbyRevert,omitempty" tf:"time_snapshot_standby_revert,omitempty"`

	// The number of CPUs allocated to the Autonomous VM cluster.
	TotalCpus *float64 `json:"totalCpus,omitempty" tf:"total_cpus,omitempty"`

	// The percentage of CPUs reserved across nodes to support node failover. Allowed values are 0%, 25%, and 50%, with 50% being the default option.
	VMFailoverReservation *float64 `json:"vmFailoverReservation,omitempty" tf:"vm_failover_reservation,omitempty"`

	// The OCID of the Oracle Cloud Infrastructure vault. This parameter and secretId are required for Customer Managed Keys.
	VaultID *string `json:"vaultId,omitempty" tf:"vault_id,omitempty"`

	// The next maintenance version preference.
	VersionPreference *string `json:"versionPreference,omitempty" tf:"version_preference,omitempty"`
}

type AutonomousContainerDatabaseAddStandbyParameters struct {

	// The Autonomous Container Database OCID.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/database/v1alpha1.AutonomousContainerDatabase
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	AutonomousContainerDatabaseID *string `json:"autonomousContainerDatabaseId,omitempty" tf:"autonomous_container_database_id,omitempty"`

	// Reference to a AutonomousContainerDatabase in database to populate autonomousContainerDatabaseId.
	// +kubebuilder:validation:Optional
	AutonomousContainerDatabaseIDRef *v1.Reference `json:"autonomousContainerDatabaseIdRef,omitempty" tf:"-"`

	// Selector for a AutonomousContainerDatabase in database to populate autonomousContainerDatabaseId.
	// +kubebuilder:validation:Optional
	AutonomousContainerDatabaseIDSelector *v1.Selector `json:"autonomousContainerDatabaseIdSelector,omitempty" tf:"-"`

	// The lag time for my preference based on data loss tolerance in seconds.
	// +kubebuilder:validation:Optional
	FastStartFailOverLagLimitInSeconds *float64 `json:"fastStartFailOverLagLimitInSeconds,omitempty" tf:"fast_start_fail_over_lag_limit_in_seconds,omitempty"`

	// Indicates whether Automatic Failover is enabled for Autonomous Container Database Dataguard Association
	// +kubebuilder:validation:Optional
	IsAutomaticFailoverEnabled *bool `json:"isAutomaticFailoverEnabled,omitempty" tf:"is_automatic_failover_enabled,omitempty"`

	// Backup options for the standby Autonomous Container Database.
	// +kubebuilder:validation:Optional
	PeerAutonomousContainerDatabaseBackupConfig []AutonomousContainerDatabaseAddStandbyPeerAutonomousContainerDatabaseBackupConfigParameters `json:"peerAutonomousContainerDatabaseBackupConfig,omitempty" tf:"peer_autonomous_container_database_backup_config,omitempty"`

	// The OCID of the compartment where the standby Autonomous Container Database will be created.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/identity/v1alpha1.Compartment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	PeerAutonomousContainerDatabaseCompartmentID *string `json:"peerAutonomousContainerDatabaseCompartmentId,omitempty" tf:"peer_autonomous_container_database_compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate peerAutonomousContainerDatabaseCompartmentId.
	// +kubebuilder:validation:Optional
	PeerAutonomousContainerDatabaseCompartmentIDRef *v1.Reference `json:"peerAutonomousContainerDatabaseCompartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate peerAutonomousContainerDatabaseCompartmentId.
	// +kubebuilder:validation:Optional
	PeerAutonomousContainerDatabaseCompartmentIDSelector *v1.Selector `json:"peerAutonomousContainerDatabaseCompartmentIdSelector,omitempty" tf:"-"`

	// The display name for the peer Autonomous Container Database.
	// +kubebuilder:validation:Optional
	PeerAutonomousContainerDatabaseDisplayName *string `json:"peerAutonomousContainerDatabaseDisplayName,omitempty" tf:"peer_autonomous_container_database_display_name,omitempty"`

	// The OCID of the peer Autonomous Exadata VM Cluster.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/database/v1alpha1.AutonomousVmCluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	PeerAutonomousVMClusterID *string `json:"peerAutonomousVmClusterId,omitempty" tf:"peer_autonomous_vm_cluster_id,omitempty"`

	// Reference to a AutonomousVmCluster in database to populate peerAutonomousVmClusterId.
	// +kubebuilder:validation:Optional
	PeerAutonomousVMClusterIDRef *v1.Reference `json:"peerAutonomousVmClusterIdRef,omitempty" tf:"-"`

	// Selector for a AutonomousVmCluster in database to populate peerAutonomousVmClusterId.
	// +kubebuilder:validation:Optional
	PeerAutonomousVMClusterIDSelector *v1.Selector `json:"peerAutonomousVmClusterIdSelector,omitempty" tf:"-"`

	// The OCID of the peer cloud Autonomous Exadata VM Cluster.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/database/v1alpha1.CloudAutonomousVmCluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	PeerCloudAutonomousVMClusterID *string `json:"peerCloudAutonomousVmClusterId,omitempty" tf:"peer_cloud_autonomous_vm_cluster_id,omitempty"`

	// Reference to a CloudAutonomousVmCluster in database to populate peerCloudAutonomousVmClusterId.
	// +kubebuilder:validation:Optional
	PeerCloudAutonomousVMClusterIDRef *v1.Reference `json:"peerCloudAutonomousVmClusterIdRef,omitempty" tf:"-"`

	// Selector for a CloudAutonomousVmCluster in database to populate peerCloudAutonomousVmClusterId.
	// +kubebuilder:validation:Optional
	PeerCloudAutonomousVMClusterIDSelector *v1.Selector `json:"peerCloudAutonomousVmClusterIdSelector,omitempty" tf:"-"`

	// Specifies the DB_UNIQUE_NAME of the peer database to be created.
	// +kubebuilder:validation:Optional
	PeerDBUniqueName *string `json:"peerDbUniqueName,omitempty" tf:"peer_db_unique_name,omitempty"`

	// The protection mode of this Autonomous Data Guard association. For more information, see Oracle Data Guard Protection Modes in the Oracle Data Guard documentation.
	// +kubebuilder:validation:Optional
	ProtectionMode *string `json:"protectionMode,omitempty" tf:"protection_mode,omitempty"`

	// The scheduling detail for the quarterly maintenance window of the standby Autonomous Container Database. This value represents the number of days before scheduled maintenance of the primary database.
	// +kubebuilder:validation:Optional
	StandbyMaintenanceBufferInDays *float64 `json:"standbyMaintenanceBufferInDays,omitempty" tf:"standby_maintenance_buffer_in_days,omitempty"`
}

type AutonomousContainerDatabaseAddStandbyPeerAutonomousContainerDatabaseBackupConfigBackupDestinationDetailsInitParameters struct {

	// Defines the automatic and manual backup retention policy for the Autonomous Database termination.  The retention policy set on the Autonomous Container Database is not applicable for cross region remote backups and backups hosted on recovery Appliance backup destination. Options are 'RETAIN_PER_RETENTION_WINDOW' or 'RETAIN_FOR_72_HOURS'.The default value is 'RETAIN_FOR_72_HOURS'.
	BackupRetentionPolicyOnTerminate *string `json:"backupRetentionPolicyOnTerminate,omitempty" tf:"backup_retention_policy_on_terminate,omitempty"`

	// The OCID of the DBRS policy used for backup.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/identity/v1alpha1.Policy
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	DbrsPolicyID *string `json:"dbrsPolicyId,omitempty" tf:"dbrs_policy_id,omitempty"`

	// Reference to a Policy in identity to populate dbrsPolicyId.
	// +kubebuilder:validation:Optional
	DbrsPolicyIDRef *v1.Reference `json:"dbrsPolicyIdRef,omitempty" tf:"-"`

	// Selector for a Policy in identity to populate dbrsPolicyId.
	// +kubebuilder:validation:Optional
	DbrsPolicyIDSelector *v1.Selector `json:"dbrsPolicyIdSelector,omitempty" tf:"-"`

	// The OCID of the backup destination.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Proxy URL to connect to object store.
	InternetProxy *string `json:"internetProxy,omitempty" tf:"internet_proxy,omitempty"`

	// Indicates if backup retention is locked for all the database backups in the Autonomous Container Database (ACD). The retention window cannot be decreased if the backup retention lock is enabled. Once applied on the Autonomous Container Database, the retention lock cannot be removed, or the retention period cannot be decreased after a 14-day period. If the backup is a Long Term Backup and retention lock is enabled, the backup cannot be deleted and must expire. The retention lock set on the Autonomous Container Database is not applicable for cross region remote backups and backups hosted on recovery Appliance backup destination.
	IsRetentionLockEnabled *bool `json:"isRetentionLockEnabled,omitempty" tf:"is_retention_lock_enabled,omitempty"`

	// Type of the database backup destination.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// For a RECOVERY_APPLIANCE backup destination, the password for the VPC user that is used to access the Recovery Appliance.
	VPCPasswordSecretRef *v1.SecretKeySelector `json:"vpcPasswordSecretRef,omitempty" tf:"-"`

	// For a RECOVERY_APPLIANCE backup destination, the Virtual Private Catalog (VPC) user that is used to access the Recovery Appliance.
	VPCUser *string `json:"vpcUser,omitempty" tf:"vpc_user,omitempty"`
}

type AutonomousContainerDatabaseAddStandbyPeerAutonomousContainerDatabaseBackupConfigBackupDestinationDetailsObservation struct {

	// Defines the automatic and manual backup retention policy for the Autonomous Database termination.  The retention policy set on the Autonomous Container Database is not applicable for cross region remote backups and backups hosted on recovery Appliance backup destination. Options are 'RETAIN_PER_RETENTION_WINDOW' or 'RETAIN_FOR_72_HOURS'.The default value is 'RETAIN_FOR_72_HOURS'.
	BackupRetentionPolicyOnTerminate *string `json:"backupRetentionPolicyOnTerminate,omitempty" tf:"backup_retention_policy_on_terminate,omitempty"`

	// The OCID of the DBRS policy used for backup.
	DbrsPolicyID *string `json:"dbrsPolicyId,omitempty" tf:"dbrs_policy_id,omitempty"`

	// The OCID of the backup destination.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Proxy URL to connect to object store.
	InternetProxy *string `json:"internetProxy,omitempty" tf:"internet_proxy,omitempty"`

	// Indicates if backup retention is locked for all the database backups in the Autonomous Container Database (ACD). The retention window cannot be decreased if the backup retention lock is enabled. Once applied on the Autonomous Container Database, the retention lock cannot be removed, or the retention period cannot be decreased after a 14-day period. If the backup is a Long Term Backup and retention lock is enabled, the backup cannot be deleted and must expire. The retention lock set on the Autonomous Container Database is not applicable for cross region remote backups and backups hosted on recovery Appliance backup destination.
	IsRetentionLockEnabled *bool `json:"isRetentionLockEnabled,omitempty" tf:"is_retention_lock_enabled,omitempty"`

	// Type of the database backup destination.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// For a RECOVERY_APPLIANCE backup destination, the Virtual Private Catalog (VPC) user that is used to access the Recovery Appliance.
	VPCUser *string `json:"vpcUser,omitempty" tf:"vpc_user,omitempty"`
}

type AutonomousContainerDatabaseAddStandbyPeerAutonomousContainerDatabaseBackupConfigBackupDestinationDetailsParameters struct {

	// Defines the automatic and manual backup retention policy for the Autonomous Database termination.  The retention policy set on the Autonomous Container Database is not applicable for cross region remote backups and backups hosted on recovery Appliance backup destination. Options are 'RETAIN_PER_RETENTION_WINDOW' or 'RETAIN_FOR_72_HOURS'.The default value is 'RETAIN_FOR_72_HOURS'.
	// +kubebuilder:validation:Optional
	BackupRetentionPolicyOnTerminate *string `json:"backupRetentionPolicyOnTerminate,omitempty" tf:"backup_retention_policy_on_terminate,omitempty"`

	// The OCID of the DBRS policy used for backup.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/identity/v1alpha1.Policy
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DbrsPolicyID *string `json:"dbrsPolicyId,omitempty" tf:"dbrs_policy_id,omitempty"`

	// Reference to a Policy in identity to populate dbrsPolicyId.
	// +kubebuilder:validation:Optional
	DbrsPolicyIDRef *v1.Reference `json:"dbrsPolicyIdRef,omitempty" tf:"-"`

	// Selector for a Policy in identity to populate dbrsPolicyId.
	// +kubebuilder:validation:Optional
	DbrsPolicyIDSelector *v1.Selector `json:"dbrsPolicyIdSelector,omitempty" tf:"-"`

	// The OCID of the backup destination.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Proxy URL to connect to object store.
	// +kubebuilder:validation:Optional
	InternetProxy *string `json:"internetProxy,omitempty" tf:"internet_proxy,omitempty"`

	// Indicates if backup retention is locked for all the database backups in the Autonomous Container Database (ACD). The retention window cannot be decreased if the backup retention lock is enabled. Once applied on the Autonomous Container Database, the retention lock cannot be removed, or the retention period cannot be decreased after a 14-day period. If the backup is a Long Term Backup and retention lock is enabled, the backup cannot be deleted and must expire. The retention lock set on the Autonomous Container Database is not applicable for cross region remote backups and backups hosted on recovery Appliance backup destination.
	// +kubebuilder:validation:Optional
	IsRetentionLockEnabled *bool `json:"isRetentionLockEnabled,omitempty" tf:"is_retention_lock_enabled,omitempty"`

	// Type of the database backup destination.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// For a RECOVERY_APPLIANCE backup destination, the password for the VPC user that is used to access the Recovery Appliance.
	// +kubebuilder:validation:Optional
	VPCPasswordSecretRef *v1.SecretKeySelector `json:"vpcPasswordSecretRef,omitempty" tf:"-"`

	// For a RECOVERY_APPLIANCE backup destination, the Virtual Private Catalog (VPC) user that is used to access the Recovery Appliance.
	// +kubebuilder:validation:Optional
	VPCUser *string `json:"vpcUser,omitempty" tf:"vpc_user,omitempty"`
}

type AutonomousContainerDatabaseAddStandbyPeerAutonomousContainerDatabaseBackupConfigInitParameters struct {

	// Backup destination details.
	BackupDestinationDetails []AutonomousContainerDatabaseAddStandbyPeerAutonomousContainerDatabaseBackupConfigBackupDestinationDetailsInitParameters `json:"backupDestinationDetails,omitempty" tf:"backup_destination_details,omitempty"`

	// Number of days between the current and the earliest point of recoverability covered by automatic backups. This value applies to automatic backups. After a new automatic backup has been created, Oracle removes old automatic backups that are created before the window. When the value is updated, it is applied to all existing automatic backups. If the number of specified days is 0 then there will be no backups.
	RecoveryWindowInDays *float64 `json:"recoveryWindowInDays,omitempty" tf:"recovery_window_in_days,omitempty"`
}

type AutonomousContainerDatabaseAddStandbyPeerAutonomousContainerDatabaseBackupConfigObservation struct {

	// Backup destination details.
	BackupDestinationDetails []AutonomousContainerDatabaseAddStandbyPeerAutonomousContainerDatabaseBackupConfigBackupDestinationDetailsObservation `json:"backupDestinationDetails,omitempty" tf:"backup_destination_details,omitempty"`

	// Number of days between the current and the earliest point of recoverability covered by automatic backups. This value applies to automatic backups. After a new automatic backup has been created, Oracle removes old automatic backups that are created before the window. When the value is updated, it is applied to all existing automatic backups. If the number of specified days is 0 then there will be no backups.
	RecoveryWindowInDays *float64 `json:"recoveryWindowInDays,omitempty" tf:"recovery_window_in_days,omitempty"`
}

type AutonomousContainerDatabaseAddStandbyPeerAutonomousContainerDatabaseBackupConfigParameters struct {

	// Backup destination details.
	// +kubebuilder:validation:Optional
	BackupDestinationDetails []AutonomousContainerDatabaseAddStandbyPeerAutonomousContainerDatabaseBackupConfigBackupDestinationDetailsParameters `json:"backupDestinationDetails,omitempty" tf:"backup_destination_details,omitempty"`

	// Number of days between the current and the earliest point of recoverability covered by automatic backups. This value applies to automatic backups. After a new automatic backup has been created, Oracle removes old automatic backups that are created before the window. When the value is updated, it is applied to all existing automatic backups. If the number of specified days is 0 then there will be no backups.
	// +kubebuilder:validation:Optional
	RecoveryWindowInDays *float64 `json:"recoveryWindowInDays,omitempty" tf:"recovery_window_in_days,omitempty"`
}

type BackupConfigBackupDestinationDetailsInitParameters struct {
}

type BackupConfigBackupDestinationDetailsObservation struct {

	// Defines the automatic and manual backup retention policy for the Autonomous Database termination.  The retention policy set on the Autonomous Container Database is not applicable for cross region remote backups and backups hosted on recovery Appliance backup destination. Options are 'RETAIN_PER_RETENTION_WINDOW' or 'RETAIN_FOR_72_HOURS'.The default value is 'RETAIN_FOR_72_HOURS'.
	BackupRetentionPolicyOnTerminate *string `json:"backupRetentionPolicyOnTerminate,omitempty" tf:"backup_retention_policy_on_terminate,omitempty"`

	// The OCID of the DBRS policy used for backup.
	DbrsPolicyID *string `json:"dbrsPolicyId,omitempty" tf:"dbrs_policy_id,omitempty"`

	// The OCID of the backup destination.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Proxy URL to connect to object store.
	InternetProxy *string `json:"internetProxy,omitempty" tf:"internet_proxy,omitempty"`

	// Indicates if backup retention is locked for all the database backups in the Autonomous Container Database (ACD). The retention window cannot be decreased if the backup retention lock is enabled. Once applied on the Autonomous Container Database, the retention lock cannot be removed, or the retention period cannot be decreased after a 14-day period. If the backup is a Long Term Backup and retention lock is enabled, the backup cannot be deleted and must expire. The retention lock set on the Autonomous Container Database is not applicable for cross region remote backups and backups hosted on recovery Appliance backup destination.
	IsRetentionLockEnabled *bool `json:"isRetentionLockEnabled,omitempty" tf:"is_retention_lock_enabled,omitempty"`

	// Type of the database backup destination.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// For a RECOVERY_APPLIANCE backup destination, the password for the VPC user that is used to access the Recovery Appliance.
	VPCPassword *string `json:"vpcPassword,omitempty" tf:"vpc_password,omitempty"`

	// For a RECOVERY_APPLIANCE backup destination, the Virtual Private Catalog (VPC) user that is used to access the Recovery Appliance.
	VPCUser *string `json:"vpcUser,omitempty" tf:"vpc_user,omitempty"`
}

type BackupConfigBackupDestinationDetailsParameters struct {
}

type MaintenanceWindowDaysOfWeekInitParameters struct {
}

type MaintenanceWindowDaysOfWeekObservation struct {

	// Name of the day of the week.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MaintenanceWindowDaysOfWeekParameters struct {
}

type MaintenanceWindowMonthsInitParameters struct {
}

type MaintenanceWindowMonthsObservation struct {

	// Name of the day of the week.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MaintenanceWindowMonthsParameters struct {
}

// AutonomousContainerDatabaseAddStandbySpec defines the desired state of AutonomousContainerDatabaseAddStandby
type AutonomousContainerDatabaseAddStandbySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AutonomousContainerDatabaseAddStandbyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AutonomousContainerDatabaseAddStandbyInitParameters `json:"initProvider,omitempty"`
}

// AutonomousContainerDatabaseAddStandbyStatus defines the observed state of AutonomousContainerDatabaseAddStandby.
type AutonomousContainerDatabaseAddStandbyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AutonomousContainerDatabaseAddStandbyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AutonomousContainerDatabaseAddStandby is the Schema for the AutonomousContainerDatabaseAddStandbys API. Provides the Autonomous Container Database Add Standby resource in Oracle Cloud Infrastructure Database service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type AutonomousContainerDatabaseAddStandby struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AutonomousContainerDatabaseAddStandbySpec   `json:"spec"`
	Status            AutonomousContainerDatabaseAddStandbyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AutonomousContainerDatabaseAddStandbyList contains a list of AutonomousContainerDatabaseAddStandbys
type AutonomousContainerDatabaseAddStandbyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AutonomousContainerDatabaseAddStandby `json:"items"`
}

// Repository type metadata.
var (
	AutonomousContainerDatabaseAddStandby_Kind             = "AutonomousContainerDatabaseAddStandby"
	AutonomousContainerDatabaseAddStandby_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AutonomousContainerDatabaseAddStandby_Kind}.String()
	AutonomousContainerDatabaseAddStandby_KindAPIVersion   = AutonomousContainerDatabaseAddStandby_Kind + "." + CRDGroupVersion.String()
	AutonomousContainerDatabaseAddStandby_GroupVersionKind = CRDGroupVersion.WithKind(AutonomousContainerDatabaseAddStandby_Kind)
)

func init() {
	SchemeBuilder.Register(&AutonomousContainerDatabaseAddStandby{}, &AutonomousContainerDatabaseAddStandbyList{})
}
