/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ManagementCloudDbHomeInitParameters struct {

	// The OCID of the cloud database home.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/database/v1alpha1.ManagementCloudDbHome
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	CloudDBHomeID *string `json:"cloudDbHomeId,omitempty" tf:"cloud_db_home_id,omitempty"`

	// Reference to a ManagementCloudDbHome in database to populate cloudDbHomeId.
	// +kubebuilder:validation:Optional
	CloudDBHomeIDRef *v1.Reference `json:"cloudDbHomeIdRef,omitempty" tf:"-"`

	// Selector for a ManagementCloudDbHome in database to populate cloudDbHomeId.
	// +kubebuilder:validation:Optional
	CloudDBHomeIDSelector *v1.Selector `json:"cloudDbHomeIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`
}

type ManagementCloudDbHomeObservation struct {

	// The additional details of the DB home defined in {"key": "value"} format. Example: {"bar-key": "value"}
	// +mapType=granular
	AdditionalDetails map[string]*string `json:"additionalDetails,omitempty" tf:"additional_details,omitempty"`

	// The OCID of the cloud database home.
	CloudDBHomeID *string `json:"cloudDbHomeId,omitempty" tf:"cloud_db_home_id,omitempty"`

	// The OCID of the cloud DB system that the DB home is a part of.
	CloudDBSystemID *string `json:"cloudDbSystemId,omitempty" tf:"cloud_db_system_id,omitempty"`

	// The OCID of the compartment.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// The name of the cloud DB home.
	ComponentName *string `json:"componentName,omitempty" tf:"component_name,omitempty"`

	// The OCID of the cloud DB home in DBaas service.
	DbaasID *string `json:"dbaasId,omitempty" tf:"dbaas_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// The user-friendly name for the cloud DB home. The name does not have to be unique.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The location of the DB home.
	HomeDirectory *string `json:"homeDirectory,omitempty" tf:"home_directory,omitempty"`

	// The OCID of the cloud DB home.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Additional information about the current lifecycle state.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// The current lifecycle state of the cloud DB home.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. System tags can be viewed by users, but can only be created by the system.  Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The date and time the cloud DB home was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The date and time the cloud DB home was last updated.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type ManagementCloudDbHomeParameters struct {

	// The OCID of the cloud database home.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/database/v1alpha1.ManagementCloudDbHome
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	CloudDBHomeID *string `json:"cloudDbHomeId,omitempty" tf:"cloud_db_home_id,omitempty"`

	// Reference to a ManagementCloudDbHome in database to populate cloudDbHomeId.
	// +kubebuilder:validation:Optional
	CloudDBHomeIDRef *v1.Reference `json:"cloudDbHomeIdRef,omitempty" tf:"-"`

	// Selector for a ManagementCloudDbHome in database to populate cloudDbHomeId.
	// +kubebuilder:validation:Optional
	CloudDBHomeIDSelector *v1.Selector `json:"cloudDbHomeIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`
}

// ManagementCloudDbHomeSpec defines the desired state of ManagementCloudDbHome
type ManagementCloudDbHomeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ManagementCloudDbHomeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ManagementCloudDbHomeInitParameters `json:"initProvider,omitempty"`
}

// ManagementCloudDbHomeStatus defines the observed state of ManagementCloudDbHome.
type ManagementCloudDbHomeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ManagementCloudDbHomeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ManagementCloudDbHome is the Schema for the ManagementCloudDbHomes API. Provides the Cloud Db Home resource in Oracle Cloud Infrastructure Database Management service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type ManagementCloudDbHome struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ManagementCloudDbHomeSpec   `json:"spec"`
	Status            ManagementCloudDbHomeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ManagementCloudDbHomeList contains a list of ManagementCloudDbHomes
type ManagementCloudDbHomeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ManagementCloudDbHome `json:"items"`
}

// Repository type metadata.
var (
	ManagementCloudDbHome_Kind             = "ManagementCloudDbHome"
	ManagementCloudDbHome_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ManagementCloudDbHome_Kind}.String()
	ManagementCloudDbHome_KindAPIVersion   = ManagementCloudDbHome_Kind + "." + CRDGroupVersion.String()
	ManagementCloudDbHome_GroupVersionKind = CRDGroupVersion.WithKind(ManagementCloudDbHome_Kind)
)

func init() {
	SchemeBuilder.Register(&ManagementCloudDbHome{}, &ManagementCloudDbHomeList{})
}
