/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DetailsExecutionDetailsContentInitParameters struct {

	// (Updatable) Bucket Name.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/datacatalog/v1alpha1.Catalog
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	CatalogID *string `json:"catalogId,omitempty" tf:"catalog_id,omitempty"`

	// Reference to a Catalog in datacatalog to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDRef *v1.Reference `json:"catalogIdRef,omitempty" tf:"-"`

	// Selector for a Catalog in datacatalog to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDSelector *v1.Selector `json:"catalogIdSelector,omitempty" tf:"-"`

	// (Updatable) md5 checksum of the artifact.
	Checksum *string `json:"checksum,omitempty" tf:"checksum,omitempty"`

	// (Updatable) Namespace.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (Updatable) Object Name.
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// (Updatable) Content Source type details.
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`
}

type DetailsExecutionDetailsContentObservation struct {

	// (Updatable) Bucket Name.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	CatalogID *string `json:"catalogId,omitempty" tf:"catalog_id,omitempty"`

	// (Updatable) md5 checksum of the artifact.
	Checksum *string `json:"checksum,omitempty" tf:"checksum,omitempty"`

	// (Updatable) Namespace.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (Updatable) Object Name.
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// (Updatable) Content Source type details.
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`
}

type DetailsExecutionDetailsContentParameters struct {

	// (Updatable) Bucket Name.
	// +kubebuilder:validation:Optional
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/datacatalog/v1alpha1.Catalog
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	CatalogID *string `json:"catalogId,omitempty" tf:"catalog_id,omitempty"`

	// Reference to a Catalog in datacatalog to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDRef *v1.Reference `json:"catalogIdRef,omitempty" tf:"-"`

	// Selector for a Catalog in datacatalog to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDSelector *v1.Selector `json:"catalogIdSelector,omitempty" tf:"-"`

	// (Updatable) md5 checksum of the artifact.
	// +kubebuilder:validation:Optional
	Checksum *string `json:"checksum,omitempty" tf:"checksum,omitempty"`

	// (Updatable) Namespace.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (Updatable) Object Name.
	// +kubebuilder:validation:Optional
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// (Updatable) Content Source type details.
	// +kubebuilder:validation:Optional
	SourceType *string `json:"sourceType" tf:"source_type,omitempty"`
}

type DetailsExecutionDetailsCredentialsInitParameters struct {

	// (Applicable when execution_type=SCRIPT) (Updatable) A user-friendly name. Does not have to be unique, and it's changeable. Avoid entering confidential information.  Example: My new resource
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) The OCID of the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type DetailsExecutionDetailsCredentialsObservation struct {

	// (Applicable when execution_type=SCRIPT) (Updatable) A user-friendly name. Does not have to be unique, and it's changeable. Avoid entering confidential information.  Example: My new resource
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) The OCID of the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type DetailsExecutionDetailsCredentialsParameters struct {

	// (Applicable when execution_type=SCRIPT) (Updatable) A user-friendly name. Does not have to be unique, and it's changeable. Avoid entering confidential information.  Example: My new resource
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) The OCID of the resource.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type DetailsExecutionDetailsInitParameters struct {

	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/datacatalog/v1alpha1.Catalog
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	CatalogID *string `json:"catalogId,omitempty" tf:"catalog_id,omitempty"`

	// Reference to a Catalog in datacatalog to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDRef *v1.Reference `json:"catalogIdRef,omitempty" tf:"-"`

	// Selector for a Catalog in datacatalog to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDSelector *v1.Selector `json:"catalogIdSelector,omitempty" tf:"-"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Optional command to execute the content. You can provide any commands/arguments that can't be part of the script.
	Command *string `json:"command,omitempty" tf:"command,omitempty"`

	ConfigFile *string `json:"configFile,omitempty" tf:"config_file,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Content Source details.
	Content []DetailsExecutionDetailsContentInitParameters `json:"content,omitempty" tf:"content,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Credentials required for executing the task.
	Credentials []DetailsExecutionDetailsCredentialsInitParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// (Updatable) Endpoint to be invoked.
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// (Updatable) The action type of the task
	ExecutionType *string `json:"executionType,omitempty" tf:"execution_type,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Is the Content an executable file?
	IsExecutableContent *bool `json:"isExecutableContent,omitempty" tf:"is_executable_content,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Is the script locked to prevent changes directly in Object Storage?
	IsLocked *bool `json:"isLocked,omitempty" tf:"is_locked,omitempty"`

	// (applicable when execution_type=provider) (updatable) is read output variable enabled
	IsReadOutputVariableEnabled *bool `json:"isReadOutputVariableEnabled,omitempty" tf:"is_read_output_variable_enabled,omitempty"`

	// (Updatable) The list of system variables.
	SystemVariables []*string `json:"systemVariables,omitempty" tf:"system_variables,omitempty"`

	// (Updatable) OCID of the compartment to which the resource belongs to.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	TargetCompartmentID *string `json:"targetCompartmentId,omitempty" tf:"target_compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate targetCompartmentId.
	// +kubebuilder:validation:Optional
	TargetCompartmentIDRef *v1.Reference `json:"targetCompartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate targetCompartmentId.
	// +kubebuilder:validation:Optional
	TargetCompartmentIDSelector *v1.Selector `json:"targetCompartmentIdSelector,omitempty" tf:"-"`

	// (Applicable when execution_type=SCRIPT) (Updatable) The variable of the task. At least one of the dynamicArguments or output needs to be provided.
	Variables []DetailsExecutionDetailsVariablesInitParameters `json:"variables,omitempty" tf:"variables,omitempty"`
}

type DetailsExecutionDetailsObservation struct {
	CatalogID *string `json:"catalogId,omitempty" tf:"catalog_id,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Optional command to execute the content. You can provide any commands/arguments that can't be part of the script.
	Command *string `json:"command,omitempty" tf:"command,omitempty"`

	ConfigFile *string `json:"configFile,omitempty" tf:"config_file,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Content Source details.
	Content []DetailsExecutionDetailsContentObservation `json:"content,omitempty" tf:"content,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Credentials required for executing the task.
	Credentials []DetailsExecutionDetailsCredentialsObservation `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// (Updatable) Endpoint to be invoked.
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// (Updatable) The action type of the task
	ExecutionType *string `json:"executionType,omitempty" tf:"execution_type,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Is the Content an executable file?
	IsExecutableContent *bool `json:"isExecutableContent,omitempty" tf:"is_executable_content,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Is the script locked to prevent changes directly in Object Storage?
	IsLocked *bool `json:"isLocked,omitempty" tf:"is_locked,omitempty"`

	// (applicable when execution_type=provider) (updatable) is read output variable enabled
	IsReadOutputVariableEnabled *bool `json:"isReadOutputVariableEnabled,omitempty" tf:"is_read_output_variable_enabled,omitempty"`

	// (Updatable) The list of system variables.
	SystemVariables []*string `json:"systemVariables,omitempty" tf:"system_variables,omitempty"`

	// (Updatable) OCID of the compartment to which the resource belongs to.
	TargetCompartmentID *string `json:"targetCompartmentId,omitempty" tf:"target_compartment_id,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) The variable of the task. At least one of the dynamicArguments or output needs to be provided.
	Variables []DetailsExecutionDetailsVariablesObservation `json:"variables,omitempty" tf:"variables,omitempty"`
}

type DetailsExecutionDetailsParameters struct {

	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/datacatalog/v1alpha1.Catalog
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	CatalogID *string `json:"catalogId,omitempty" tf:"catalog_id,omitempty"`

	// Reference to a Catalog in datacatalog to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDRef *v1.Reference `json:"catalogIdRef,omitempty" tf:"-"`

	// Selector for a Catalog in datacatalog to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDSelector *v1.Selector `json:"catalogIdSelector,omitempty" tf:"-"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Optional command to execute the content. You can provide any commands/arguments that can't be part of the script.
	// +kubebuilder:validation:Optional
	Command *string `json:"command,omitempty" tf:"command,omitempty"`

	// +kubebuilder:validation:Optional
	ConfigFile *string `json:"configFile,omitempty" tf:"config_file,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Content Source details.
	// +kubebuilder:validation:Optional
	Content []DetailsExecutionDetailsContentParameters `json:"content,omitempty" tf:"content,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Credentials required for executing the task.
	// +kubebuilder:validation:Optional
	Credentials []DetailsExecutionDetailsCredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// (Updatable) Endpoint to be invoked.
	// +kubebuilder:validation:Optional
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// (Updatable) The action type of the task
	// +kubebuilder:validation:Optional
	ExecutionType *string `json:"executionType" tf:"execution_type,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Is the Content an executable file?
	// +kubebuilder:validation:Optional
	IsExecutableContent *bool `json:"isExecutableContent,omitempty" tf:"is_executable_content,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) Is the script locked to prevent changes directly in Object Storage?
	// +kubebuilder:validation:Optional
	IsLocked *bool `json:"isLocked,omitempty" tf:"is_locked,omitempty"`

	// (applicable when execution_type=provider) (updatable) is read output variable enabled
	// +kubebuilder:validation:Optional
	IsReadOutputVariableEnabled *bool `json:"isReadOutputVariableEnabled,omitempty" tf:"is_read_output_variable_enabled,omitempty"`

	// (Updatable) The list of system variables.
	// +kubebuilder:validation:Optional
	SystemVariables []*string `json:"systemVariables,omitempty" tf:"system_variables,omitempty"`

	// (Updatable) OCID of the compartment to which the resource belongs to.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	TargetCompartmentID *string `json:"targetCompartmentId,omitempty" tf:"target_compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate targetCompartmentId.
	// +kubebuilder:validation:Optional
	TargetCompartmentIDRef *v1.Reference `json:"targetCompartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate targetCompartmentId.
	// +kubebuilder:validation:Optional
	TargetCompartmentIDSelector *v1.Selector `json:"targetCompartmentIdSelector,omitempty" tf:"-"`

	// (Applicable when execution_type=SCRIPT) (Updatable) The variable of the task. At least one of the dynamicArguments or output needs to be provided.
	// +kubebuilder:validation:Optional
	Variables []DetailsExecutionDetailsVariablesParameters `json:"variables,omitempty" tf:"variables,omitempty"`
}

type DetailsExecutionDetailsVariablesInitParameters struct {

	// (Applicable when execution_type=SCRIPT) (Updatable) The input variables for the task.
	InputVariables []ExecutionDetailsVariablesInputVariablesInitParameters `json:"inputVariables,omitempty" tf:"input_variables,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) The list of output variables.
	OutputVariables []*string `json:"outputVariables,omitempty" tf:"output_variables,omitempty"`
}

type DetailsExecutionDetailsVariablesObservation struct {

	// (Applicable when execution_type=SCRIPT) (Updatable) The input variables for the task.
	InputVariables []ExecutionDetailsVariablesInputVariablesObservation `json:"inputVariables,omitempty" tf:"input_variables,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) The list of output variables.
	OutputVariables []*string `json:"outputVariables,omitempty" tf:"output_variables,omitempty"`
}

type DetailsExecutionDetailsVariablesParameters struct {

	// (Applicable when execution_type=SCRIPT) (Updatable) The input variables for the task.
	// +kubebuilder:validation:Optional
	InputVariables []ExecutionDetailsVariablesInputVariablesParameters `json:"inputVariables,omitempty" tf:"input_variables,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) The list of output variables.
	// +kubebuilder:validation:Optional
	OutputVariables []*string `json:"outputVariables,omitempty" tf:"output_variables,omitempty"`
}

type DetailsPropertiesInitParameters struct {

	// (Updatable) The number of retries allowed.
	NumRetries *float64 `json:"numRetries,omitempty" tf:"num_retries,omitempty"`

	// (Updatable) The timeout in seconds for the task.
	TimeoutInSeconds *float64 `json:"timeoutInSeconds,omitempty" tf:"timeout_in_seconds,omitempty"`
}

type DetailsPropertiesObservation struct {

	// (Updatable) The number of retries allowed.
	NumRetries *float64 `json:"numRetries,omitempty" tf:"num_retries,omitempty"`

	// (Updatable) The timeout in seconds for the task.
	TimeoutInSeconds *float64 `json:"timeoutInSeconds,omitempty" tf:"timeout_in_seconds,omitempty"`
}

type DetailsPropertiesParameters struct {

	// (Updatable) The number of retries allowed.
	// +kubebuilder:validation:Optional
	NumRetries *float64 `json:"numRetries" tf:"num_retries,omitempty"`

	// (Updatable) The timeout in seconds for the task.
	// +kubebuilder:validation:Optional
	TimeoutInSeconds *float64 `json:"timeoutInSeconds" tf:"timeout_in_seconds,omitempty"`
}

type ExecutionDetailsVariablesInputVariablesInitParameters struct {

	// (Updatable) A user-friendly description. To provide some insight about the resource. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The name of the argument.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Updatable) Input argument Type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ExecutionDetailsVariablesInputVariablesObservation struct {

	// (Updatable) A user-friendly description. To provide some insight about the resource. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The name of the argument.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Updatable) Input argument Type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ExecutionDetailsVariablesInputVariablesParameters struct {

	// (Updatable) A user-friendly description. To provide some insight about the resource. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The name of the argument.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Updatable) Input argument Type.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type TaskRecordDetailsInitParameters_2 struct {

	// (Updatable) Execution details.
	ExecutionDetails []DetailsExecutionDetailsInitParameters `json:"executionDetails,omitempty" tf:"execution_details,omitempty"`

	// (Updatable) Is this an Apply Subject Task?  Set this to true for a Patch Execution Task which applies patches(subjects) on a target.
	IsApplySubjectTask *bool `json:"isApplySubjectTask,omitempty" tf:"is_apply_subject_task,omitempty"`

	// (Updatable) Is this a discovery output task?
	IsDiscoveryOutputTask *bool `json:"isDiscoveryOutputTask,omitempty" tf:"is_discovery_output_task,omitempty"`

	// (Updatable) The lifecycle operation performed by the runbook.
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// (Updatable) The OS for the task
	OsType *string `json:"osType,omitempty" tf:"os_type,omitempty"`

	// (Updatable) The platform of the runbook.
	Platform *string `json:"platform,omitempty" tf:"platform,omitempty"`

	// (Updatable) The properties of the task.
	Properties []DetailsPropertiesInitParameters `json:"properties,omitempty" tf:"properties,omitempty"`

	// (Updatable) The scope of the task
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type TaskRecordDetailsObservation_2 struct {

	// (Updatable) Execution details.
	ExecutionDetails []DetailsExecutionDetailsObservation `json:"executionDetails,omitempty" tf:"execution_details,omitempty"`

	// (Updatable) Is this an Apply Subject Task?  Set this to true for a Patch Execution Task which applies patches(subjects) on a target.
	IsApplySubjectTask *bool `json:"isApplySubjectTask,omitempty" tf:"is_apply_subject_task,omitempty"`

	// (Updatable) Is this a discovery output task?
	IsDiscoveryOutputTask *bool `json:"isDiscoveryOutputTask,omitempty" tf:"is_discovery_output_task,omitempty"`

	// (Updatable) The lifecycle operation performed by the runbook.
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// (Updatable) The OS for the task
	OsType *string `json:"osType,omitempty" tf:"os_type,omitempty"`

	// (Updatable) The platform of the runbook.
	Platform *string `json:"platform,omitempty" tf:"platform,omitempty"`

	// (Updatable) The properties of the task.
	Properties []DetailsPropertiesObservation `json:"properties,omitempty" tf:"properties,omitempty"`

	// (Updatable) The scope of the task
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type TaskRecordDetailsParameters_2 struct {

	// (Updatable) Execution details.
	// +kubebuilder:validation:Optional
	ExecutionDetails []DetailsExecutionDetailsParameters `json:"executionDetails" tf:"execution_details,omitempty"`

	// (Updatable) Is this an Apply Subject Task?  Set this to true for a Patch Execution Task which applies patches(subjects) on a target.
	// +kubebuilder:validation:Optional
	IsApplySubjectTask *bool `json:"isApplySubjectTask,omitempty" tf:"is_apply_subject_task,omitempty"`

	// (Updatable) Is this a discovery output task?
	// +kubebuilder:validation:Optional
	IsDiscoveryOutputTask *bool `json:"isDiscoveryOutputTask,omitempty" tf:"is_discovery_output_task,omitempty"`

	// (Updatable) The lifecycle operation performed by the runbook.
	// +kubebuilder:validation:Optional
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// (Updatable) The OS for the task
	// +kubebuilder:validation:Optional
	OsType *string `json:"osType,omitempty" tf:"os_type,omitempty"`

	// (Updatable) The platform of the runbook.
	// +kubebuilder:validation:Optional
	Platform *string `json:"platform,omitempty" tf:"platform,omitempty"`

	// (Updatable) The properties of the task.
	// +kubebuilder:validation:Optional
	Properties []DetailsPropertiesParameters `json:"properties,omitempty" tf:"properties,omitempty"`

	// (Updatable) The scope of the task
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope" tf:"scope,omitempty"`
}

type TaskRecordInitParameters struct {

	// (Updatable)
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) A user-friendly description. To provide some insight about the resource. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The details of the task.
	Details []TaskRecordDetailsInitParameters_2 `json:"details,omitempty" tf:"details,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) A user-friendly name. Does not have to be unique, and it's changeable. Avoid entering confidential information.  Example: My new resource
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`
}

type TaskRecordObservation struct {

	// (Updatable)
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) A user-friendly description. To provide some insight about the resource. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The details of the task.
	Details []TaskRecordDetailsObservation_2 `json:"details,omitempty" tf:"details,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) A user-friendly name. Does not have to be unique, and it's changeable. Avoid entering confidential information.  Example: My new resource
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) The OCID of the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A message describing the current state in more detail. For example, can be used to provide actionable information for a resource in Failed state.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// Associated region
	ResourceRegion *string `json:"resourceRegion,omitempty" tf:"resource_region,omitempty"`

	// The current state of the task record.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace. Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The time this resource was created. An RFC3339 formatted datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The time this resource was last updated. An RFC3339 formatted datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// (Updatable) Input argument Type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The version of the task record.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type TaskRecordParameters struct {

	// (Updatable)
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) A user-friendly description. To provide some insight about the resource. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The details of the task.
	// +kubebuilder:validation:Optional
	Details []TaskRecordDetailsParameters_2 `json:"details,omitempty" tf:"details,omitempty"`

	// (Applicable when execution_type=SCRIPT) (Updatable) A user-friendly name. Does not have to be unique, and it's changeable. Avoid entering confidential information.  Example: My new resource
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`
}

// TaskRecordSpec defines the desired state of TaskRecord
type TaskRecordSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TaskRecordParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TaskRecordInitParameters `json:"initProvider,omitempty"`
}

// TaskRecordStatus defines the observed state of TaskRecord.
type TaskRecordStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TaskRecordObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TaskRecord is the Schema for the TaskRecords API. Provides the Task Record resource in Oracle Cloud Infrastructure Fleet Apps Management service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type TaskRecord struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.details) || (has(self.initProvider) && has(self.initProvider.details))",message="spec.forProvider.details is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   TaskRecordSpec   `json:"spec"`
	Status TaskRecordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TaskRecordList contains a list of TaskRecords
type TaskRecordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TaskRecord `json:"items"`
}

// Repository type metadata.
var (
	TaskRecord_Kind             = "TaskRecord"
	TaskRecord_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TaskRecord_Kind}.String()
	TaskRecord_KindAPIVersion   = TaskRecord_Kind + "." + CRDGroupVersion.String()
	TaskRecord_GroupVersionKind = CRDGroupVersion.WithKind(TaskRecord_Kind)
)

func init() {
	SchemeBuilder.Register(&TaskRecord{}, &TaskRecordList{})
}
