/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type LogAnalyticsPreferencesManagementInitParameters struct {

	// An array of tenant preference details.
	Items []LogAnalyticsPreferencesManagementItemsInitParameters `json:"items,omitempty" tf:"items,omitempty"`

	// The Logging Analytics namespace used for the request.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type LogAnalyticsPreferencesManagementItemsInitParameters struct {

	// The preference name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The preference value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type LogAnalyticsPreferencesManagementItemsObservation struct {

	// The preference name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The preference value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type LogAnalyticsPreferencesManagementItemsParameters struct {

	// The preference name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The preference value.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type LogAnalyticsPreferencesManagementObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// An array of tenant preference details.
	Items []LogAnalyticsPreferencesManagementItemsObservation `json:"items,omitempty" tf:"items,omitempty"`

	// The Logging Analytics namespace used for the request.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type LogAnalyticsPreferencesManagementParameters struct {

	// An array of tenant preference details.
	// +kubebuilder:validation:Optional
	Items []LogAnalyticsPreferencesManagementItemsParameters `json:"items,omitempty" tf:"items,omitempty"`

	// The Logging Analytics namespace used for the request.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

// LogAnalyticsPreferencesManagementSpec defines the desired state of LogAnalyticsPreferencesManagement
type LogAnalyticsPreferencesManagementSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            LogAnalyticsPreferencesManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LogAnalyticsPreferencesManagementInitParameters `json:"initProvider,omitempty"`
}

// LogAnalyticsPreferencesManagementStatus defines the observed state of LogAnalyticsPreferencesManagement.
type LogAnalyticsPreferencesManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LogAnalyticsPreferencesManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LogAnalyticsPreferencesManagement is the Schema for the LogAnalyticsPreferencesManagements API. Provides the Log Analytics Preferences Management resource in Oracle Cloud Infrastructure Log Analytics service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type LogAnalyticsPreferencesManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.__namespace__) || (has(self.initProvider) && has(self.initProvider.__namespace__))",message="spec.forProvider.namespace is a required parameter"
	Spec   LogAnalyticsPreferencesManagementSpec   `json:"spec"`
	Status LogAnalyticsPreferencesManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LogAnalyticsPreferencesManagementList contains a list of LogAnalyticsPreferencesManagements
type LogAnalyticsPreferencesManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LogAnalyticsPreferencesManagement `json:"items"`
}

// Repository type metadata.
var (
	LogAnalyticsPreferencesManagement_Kind             = "LogAnalyticsPreferencesManagement"
	LogAnalyticsPreferencesManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LogAnalyticsPreferencesManagement_Kind}.String()
	LogAnalyticsPreferencesManagement_KindAPIVersion   = LogAnalyticsPreferencesManagement_Kind + "." + CRDGroupVersion.String()
	LogAnalyticsPreferencesManagement_GroupVersionKind = CRDGroupVersion.WithKind(LogAnalyticsPreferencesManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&LogAnalyticsPreferencesManagement{}, &LogAnalyticsPreferencesManagementList{})
}
