/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type OsnInitParameters struct {

	// Availability Domain to place new OSN
	Ad *string `json:"ad,omitempty" tf:"ad,omitempty"`

	// Unique service identifier.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/blockchain/v1alpha1.BlockchainPlatform
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	BlockchainPlatformID *string `json:"blockchainPlatformId,omitempty" tf:"blockchain_platform_id,omitempty"`

	// Reference to a BlockchainPlatform in blockchain to populate blockchainPlatformId.
	// +kubebuilder:validation:Optional
	BlockchainPlatformIDRef *v1.NamespacedReference `json:"blockchainPlatformIdRef,omitempty" tf:"-"`

	// Selector for a BlockchainPlatform in blockchain to populate blockchainPlatformId.
	// +kubebuilder:validation:Optional
	BlockchainPlatformIDSelector *v1.NamespacedSelector `json:"blockchainPlatformIdSelector,omitempty" tf:"-"`

	// (Updatable) OCPU allocation parameter
	OcpuAllocationParam []OsnOcpuAllocationParamInitParameters `json:"ocpuAllocationParam,omitempty" tf:"ocpu_allocation_param,omitempty"`
}

type OsnObservation struct {

	// Availability Domain to place new OSN
	Ad *string `json:"ad,omitempty" tf:"ad,omitempty"`

	// Unique service identifier.
	BlockchainPlatformID *string `json:"blockchainPlatformId,omitempty" tf:"blockchain_platform_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) OCPU allocation parameter
	OcpuAllocationParam []OsnOcpuAllocationParamObservation `json:"ocpuAllocationParam,omitempty" tf:"ocpu_allocation_param,omitempty"`

	// OSN identifier
	OsnKey *string `json:"osnKey,omitempty" tf:"osn_key,omitempty"`

	// The current state of the OSN.
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type OsnOcpuAllocationParamInitParameters struct {

	// (Updatable) Number of OCPU allocation
	OcpuAllocationNumber *float64 `json:"ocpuAllocationNumber,omitempty" tf:"ocpu_allocation_number,omitempty"`
}

type OsnOcpuAllocationParamObservation struct {

	// (Updatable) Number of OCPU allocation
	OcpuAllocationNumber *float64 `json:"ocpuAllocationNumber,omitempty" tf:"ocpu_allocation_number,omitempty"`
}

type OsnOcpuAllocationParamParameters struct {

	// (Updatable) Number of OCPU allocation
	// +kubebuilder:validation:Optional
	OcpuAllocationNumber *float64 `json:"ocpuAllocationNumber" tf:"ocpu_allocation_number,omitempty"`
}

type OsnParameters struct {

	// Availability Domain to place new OSN
	// +kubebuilder:validation:Optional
	Ad *string `json:"ad,omitempty" tf:"ad,omitempty"`

	// Unique service identifier.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/blockchain/v1alpha1.BlockchainPlatform
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	BlockchainPlatformID *string `json:"blockchainPlatformId,omitempty" tf:"blockchain_platform_id,omitempty"`

	// Reference to a BlockchainPlatform in blockchain to populate blockchainPlatformId.
	// +kubebuilder:validation:Optional
	BlockchainPlatformIDRef *v1.NamespacedReference `json:"blockchainPlatformIdRef,omitempty" tf:"-"`

	// Selector for a BlockchainPlatform in blockchain to populate blockchainPlatformId.
	// +kubebuilder:validation:Optional
	BlockchainPlatformIDSelector *v1.NamespacedSelector `json:"blockchainPlatformIdSelector,omitempty" tf:"-"`

	// (Updatable) OCPU allocation parameter
	// +kubebuilder:validation:Optional
	OcpuAllocationParam []OsnOcpuAllocationParamParameters `json:"ocpuAllocationParam,omitempty" tf:"ocpu_allocation_param,omitempty"`
}

// OsnSpec defines the desired state of Osn
type OsnSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OsnParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OsnInitParameters `json:"initProvider,omitempty"`
}

// OsnStatus defines the observed state of Osn.
type OsnStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OsnObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Osn is the Schema for the Osns API. Provides the Osn resource in Oracle Cloud Infrastructure Blockchain service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type Osn struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ad) || (has(self.initProvider) && has(self.initProvider.ad))",message="spec.forProvider.ad is a required parameter"
	Spec   OsnSpec   `json:"spec"`
	Status OsnStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OsnList contains a list of Osns
type OsnList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Osn `json:"items"`
}

// Repository type metadata.
var (
	Osn_Kind             = "Osn"
	Osn_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Osn_Kind}.String()
	Osn_KindAPIVersion   = Osn_Kind + "." + CRDGroupVersion.String()
	Osn_GroupVersionKind = CRDGroupVersion.WithKind(Osn_Kind)
)

func init() {
	SchemeBuilder.Register(&Osn{}, &OsnList{})
}
