/*
Copyright 2022 Upbound Inc.
*/

package controller

import (
	ctrl "sigs.k8s.io/controller-runtime"

	"github.com/crossplane/upjet/pkg/controller"

	managementhubevent "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubevent"
	managementhublifecycleenvironment "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhublifecycleenvironment"
	managementhublifecyclestageattachmanagedinstancesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhublifecyclestageattachmanagedinstancesmanagement"
	managementhublifecyclestagedetachmanagedinstancesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhublifecyclestagedetachmanagedinstancesmanagement"
	managementhublifecyclestagepromotesoftwaresourcemanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhublifecyclestagepromotesoftwaresourcemanagement"
	managementhublifecyclestagerebootmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhublifecyclestagerebootmanagement"
	managementhubmanagedinstance "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstance"
	managementhubmanagedinstanceattachprofilemanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstanceattachprofilemanagement"
	managementhubmanagedinstancedetachprofilemanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstancedetachprofilemanagement"
	managementhubmanagedinstancegroup "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstancegroup"
	managementhubmanagedinstancegroupattachmanagedinstancesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstancegroupattachmanagedinstancesmanagement"
	managementhubmanagedinstancegroupattachsoftwaresourcesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstancegroupattachsoftwaresourcesmanagement"
	managementhubmanagedinstancegroupdetachmanagedinstancesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstancegroupdetachmanagedinstancesmanagement"
	managementhubmanagedinstancegroupdetachsoftwaresourcesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstancegroupdetachsoftwaresourcesmanagement"
	managementhubmanagedinstancegroupinstallpackagesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstancegroupinstallpackagesmanagement"
	managementhubmanagedinstancegroupinstallwindowsupdatesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstancegroupinstallwindowsupdatesmanagement"
	managementhubmanagedinstancegroupmanagemodulestreamsmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstancegroupmanagemodulestreamsmanagement"
	managementhubmanagedinstancegrouprebootmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstancegrouprebootmanagement"
	managementhubmanagedinstancegroupremovepackagesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstancegroupremovepackagesmanagement"
	managementhubmanagedinstancegroupupdateallpackagesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstancegroupupdateallpackagesmanagement"
	managementhubmanagedinstanceinstallwindowsupdatesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstanceinstallwindowsupdatesmanagement"
	managementhubmanagedinstancerebootmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstancerebootmanagement"
	managementhubmanagedinstanceupdatepackagesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagedinstanceupdatepackagesmanagement"
	managementhubmanagementstation "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagementstation"
	managementhubmanagementstationassociatemanagedinstancesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagementstationassociatemanagedinstancesmanagement"
	managementhubmanagementstationmirrorsynchronizemanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagementstationmirrorsynchronizemanagement"
	managementhubmanagementstationrefreshmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagementstationrefreshmanagement"
	managementhubmanagementstationsynchronizemirrorsmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubmanagementstationsynchronizemirrorsmanagement"
	managementhubprofile "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubprofile"
	managementhubprofileattachlifecyclestagemanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubprofileattachlifecyclestagemanagement"
	managementhubprofileattachmanagedinstancegroupmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubprofileattachmanagedinstancegroupmanagement"
	managementhubprofileattachmanagementstationmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubprofileattachmanagementstationmanagement"
	managementhubprofileattachsoftwaresourcesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubprofileattachsoftwaresourcesmanagement"
	managementhubprofiledetachsoftwaresourcesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubprofiledetachsoftwaresourcesmanagement"
	managementhubscheduledjob "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubscheduledjob"
	managementhubsoftwaresource "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubsoftwaresource"
	managementhubsoftwaresourceaddpackagesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubsoftwaresourceaddpackagesmanagement"
	managementhubsoftwaresourcechangeavailabilitymanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubsoftwaresourcechangeavailabilitymanagement"
	managementhubsoftwaresourcegeneratemetadatamanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubsoftwaresourcegeneratemetadatamanagement"
	managementhubsoftwaresourcemanifest "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubsoftwaresourcemanifest"
	managementhubsoftwaresourceremovepackagesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubsoftwaresourceremovepackagesmanagement"
	managementhubsoftwaresourcereplacepackagesmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubsoftwaresourcereplacepackagesmanagement"
	managementhubworkrequestrerunmanagement "github.com/oracle/provider-oci/internal/controller/osmanagement/managementhubworkrequestrerunmanagement"
)

// Setup_osmanagement creates all controllers with the supplied logger and adds them to
// the supplied manager.
func Setup_osmanagement(mgr ctrl.Manager, o controller.Options) error {
	for _, setup := range []func(ctrl.Manager, controller.Options) error{
		managementhubevent.Setup,
		managementhublifecycleenvironment.Setup,
		managementhublifecyclestageattachmanagedinstancesmanagement.Setup,
		managementhublifecyclestagedetachmanagedinstancesmanagement.Setup,
		managementhublifecyclestagepromotesoftwaresourcemanagement.Setup,
		managementhublifecyclestagerebootmanagement.Setup,
		managementhubmanagedinstance.Setup,
		managementhubmanagedinstanceattachprofilemanagement.Setup,
		managementhubmanagedinstancedetachprofilemanagement.Setup,
		managementhubmanagedinstancegroup.Setup,
		managementhubmanagedinstancegroupattachmanagedinstancesmanagement.Setup,
		managementhubmanagedinstancegroupattachsoftwaresourcesmanagement.Setup,
		managementhubmanagedinstancegroupdetachmanagedinstancesmanagement.Setup,
		managementhubmanagedinstancegroupdetachsoftwaresourcesmanagement.Setup,
		managementhubmanagedinstancegroupinstallpackagesmanagement.Setup,
		managementhubmanagedinstancegroupinstallwindowsupdatesmanagement.Setup,
		managementhubmanagedinstancegroupmanagemodulestreamsmanagement.Setup,
		managementhubmanagedinstancegrouprebootmanagement.Setup,
		managementhubmanagedinstancegroupremovepackagesmanagement.Setup,
		managementhubmanagedinstancegroupupdateallpackagesmanagement.Setup,
		managementhubmanagedinstanceinstallwindowsupdatesmanagement.Setup,
		managementhubmanagedinstancerebootmanagement.Setup,
		managementhubmanagedinstanceupdatepackagesmanagement.Setup,
		managementhubmanagementstation.Setup,
		managementhubmanagementstationassociatemanagedinstancesmanagement.Setup,
		managementhubmanagementstationmirrorsynchronizemanagement.Setup,
		managementhubmanagementstationrefreshmanagement.Setup,
		managementhubmanagementstationsynchronizemirrorsmanagement.Setup,
		managementhubprofile.Setup,
		managementhubprofileattachlifecyclestagemanagement.Setup,
		managementhubprofileattachmanagedinstancegroupmanagement.Setup,
		managementhubprofileattachmanagementstationmanagement.Setup,
		managementhubprofileattachsoftwaresourcesmanagement.Setup,
		managementhubprofiledetachsoftwaresourcesmanagement.Setup,
		managementhubscheduledjob.Setup,
		managementhubsoftwaresource.Setup,
		managementhubsoftwaresourceaddpackagesmanagement.Setup,
		managementhubsoftwaresourcechangeavailabilitymanagement.Setup,
		managementhubsoftwaresourcegeneratemetadatamanagement.Setup,
		managementhubsoftwaresourcemanifest.Setup,
		managementhubsoftwaresourceremovepackagesmanagement.Setup,
		managementhubsoftwaresourcereplacepackagesmanagement.Setup,
		managementhubworkrequestrerunmanagement.Setup,
	} {
		if err := setup(mgr, o); err != nil {
			return err
		}
	}
	return nil
}
