/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ManagementHubManagedInstanceRebootManagementInitParameters struct {

	// The OCID of the managed instance.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/osmanagement/v1alpha1.ManagementHubManagedInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	ManagedInstanceID *string `json:"managedInstanceId,omitempty" tf:"managed_instance_id,omitempty"`

	// Reference to a ManagementHubManagedInstance in osmanagement to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDRef *v1.Reference `json:"managedInstanceIdRef,omitempty" tf:"-"`

	// Selector for a ManagementHubManagedInstance in osmanagement to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDSelector *v1.Selector `json:"managedInstanceIdSelector,omitempty" tf:"-"`

	// The number of minutes the service waits for the reboot to complete. If the instance doesn't reboot within this  time, the reboot job status is set to failed.
	RebootTimeoutInMins *float64 `json:"rebootTimeoutInMins,omitempty" tf:"reboot_timeout_in_mins,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []ManagementHubManagedInstanceRebootManagementWorkRequestDetailsInitParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagementHubManagedInstanceRebootManagementObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the managed instance.
	ManagedInstanceID *string `json:"managedInstanceId,omitempty" tf:"managed_instance_id,omitempty"`

	// The number of minutes the service waits for the reboot to complete. If the instance doesn't reboot within this  time, the reboot job status is set to failed.
	RebootTimeoutInMins *float64 `json:"rebootTimeoutInMins,omitempty" tf:"reboot_timeout_in_mins,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []ManagementHubManagedInstanceRebootManagementWorkRequestDetailsObservation `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagementHubManagedInstanceRebootManagementParameters struct {

	// The OCID of the managed instance.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/osmanagement/v1alpha1.ManagementHubManagedInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ManagedInstanceID *string `json:"managedInstanceId,omitempty" tf:"managed_instance_id,omitempty"`

	// Reference to a ManagementHubManagedInstance in osmanagement to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDRef *v1.Reference `json:"managedInstanceIdRef,omitempty" tf:"-"`

	// Selector for a ManagementHubManagedInstance in osmanagement to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDSelector *v1.Selector `json:"managedInstanceIdSelector,omitempty" tf:"-"`

	// The number of minutes the service waits for the reboot to complete. If the instance doesn't reboot within this  time, the reboot job status is set to failed.
	// +kubebuilder:validation:Optional
	RebootTimeoutInMins *float64 `json:"rebootTimeoutInMins,omitempty" tf:"reboot_timeout_in_mins,omitempty"`

	// Provides the name and description of the job.
	// +kubebuilder:validation:Optional
	WorkRequestDetails []ManagementHubManagedInstanceRebootManagementWorkRequestDetailsParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagementHubManagedInstanceRebootManagementWorkRequestDetailsInitParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type ManagementHubManagedInstanceRebootManagementWorkRequestDetailsObservation struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type ManagementHubManagedInstanceRebootManagementWorkRequestDetailsParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

// ManagementHubManagedInstanceRebootManagementSpec defines the desired state of ManagementHubManagedInstanceRebootManagement
type ManagementHubManagedInstanceRebootManagementSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ManagementHubManagedInstanceRebootManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ManagementHubManagedInstanceRebootManagementInitParameters `json:"initProvider,omitempty"`
}

// ManagementHubManagedInstanceRebootManagementStatus defines the observed state of ManagementHubManagedInstanceRebootManagement.
type ManagementHubManagedInstanceRebootManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ManagementHubManagedInstanceRebootManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ManagementHubManagedInstanceRebootManagement is the Schema for the ManagementHubManagedInstanceRebootManagements API. Provides the Managed Instance Reboot Management resource in Oracle Cloud Infrastructure Os Management Hub service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type ManagementHubManagedInstanceRebootManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ManagementHubManagedInstanceRebootManagementSpec   `json:"spec"`
	Status            ManagementHubManagedInstanceRebootManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ManagementHubManagedInstanceRebootManagementList contains a list of ManagementHubManagedInstanceRebootManagements
type ManagementHubManagedInstanceRebootManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ManagementHubManagedInstanceRebootManagement `json:"items"`
}

// Repository type metadata.
var (
	ManagementHubManagedInstanceRebootManagement_Kind             = "ManagementHubManagedInstanceRebootManagement"
	ManagementHubManagedInstanceRebootManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ManagementHubManagedInstanceRebootManagement_Kind}.String()
	ManagementHubManagedInstanceRebootManagement_KindAPIVersion   = ManagementHubManagedInstanceRebootManagement_Kind + "." + CRDGroupVersion.String()
	ManagementHubManagedInstanceRebootManagement_GroupVersionKind = CRDGroupVersion.WithKind(ManagementHubManagedInstanceRebootManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&ManagementHubManagedInstanceRebootManagement{}, &ManagementHubManagedInstanceRebootManagementList{})
}
