/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"

// GetCondition of this Event.
func (mg *Event) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this Event.
func (mg *Event) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this Event.
func (mg *Event) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this Event.
func (mg *Event) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this Event.
func (mg *Event) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this Event.
func (mg *Event) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this Event.
func (mg *Event) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this Event.
func (mg *Event) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this LifecycleEnvironment.
func (mg *LifecycleEnvironment) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this LifecycleEnvironment.
func (mg *LifecycleEnvironment) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this LifecycleEnvironment.
func (mg *LifecycleEnvironment) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this LifecycleEnvironment.
func (mg *LifecycleEnvironment) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this LifecycleEnvironment.
func (mg *LifecycleEnvironment) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this LifecycleEnvironment.
func (mg *LifecycleEnvironment) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this LifecycleEnvironment.
func (mg *LifecycleEnvironment) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this LifecycleEnvironment.
func (mg *LifecycleEnvironment) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this LifecycleStageAttachManagedInstancesManagement.
func (mg *LifecycleStageAttachManagedInstancesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this LifecycleStageAttachManagedInstancesManagement.
func (mg *LifecycleStageAttachManagedInstancesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this LifecycleStageAttachManagedInstancesManagement.
func (mg *LifecycleStageAttachManagedInstancesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this LifecycleStageAttachManagedInstancesManagement.
func (mg *LifecycleStageAttachManagedInstancesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this LifecycleStageAttachManagedInstancesManagement.
func (mg *LifecycleStageAttachManagedInstancesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this LifecycleStageAttachManagedInstancesManagement.
func (mg *LifecycleStageAttachManagedInstancesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this LifecycleStageAttachManagedInstancesManagement.
func (mg *LifecycleStageAttachManagedInstancesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this LifecycleStageAttachManagedInstancesManagement.
func (mg *LifecycleStageAttachManagedInstancesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this LifecycleStageDetachManagedInstancesManagement.
func (mg *LifecycleStageDetachManagedInstancesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this LifecycleStageDetachManagedInstancesManagement.
func (mg *LifecycleStageDetachManagedInstancesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this LifecycleStageDetachManagedInstancesManagement.
func (mg *LifecycleStageDetachManagedInstancesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this LifecycleStageDetachManagedInstancesManagement.
func (mg *LifecycleStageDetachManagedInstancesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this LifecycleStageDetachManagedInstancesManagement.
func (mg *LifecycleStageDetachManagedInstancesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this LifecycleStageDetachManagedInstancesManagement.
func (mg *LifecycleStageDetachManagedInstancesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this LifecycleStageDetachManagedInstancesManagement.
func (mg *LifecycleStageDetachManagedInstancesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this LifecycleStageDetachManagedInstancesManagement.
func (mg *LifecycleStageDetachManagedInstancesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this LifecycleStagePromoteSoftwareSourceManagement.
func (mg *LifecycleStagePromoteSoftwareSourceManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this LifecycleStagePromoteSoftwareSourceManagement.
func (mg *LifecycleStagePromoteSoftwareSourceManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this LifecycleStagePromoteSoftwareSourceManagement.
func (mg *LifecycleStagePromoteSoftwareSourceManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this LifecycleStagePromoteSoftwareSourceManagement.
func (mg *LifecycleStagePromoteSoftwareSourceManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this LifecycleStagePromoteSoftwareSourceManagement.
func (mg *LifecycleStagePromoteSoftwareSourceManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this LifecycleStagePromoteSoftwareSourceManagement.
func (mg *LifecycleStagePromoteSoftwareSourceManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this LifecycleStagePromoteSoftwareSourceManagement.
func (mg *LifecycleStagePromoteSoftwareSourceManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this LifecycleStagePromoteSoftwareSourceManagement.
func (mg *LifecycleStagePromoteSoftwareSourceManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this LifecycleStageRebootManagement.
func (mg *LifecycleStageRebootManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this LifecycleStageRebootManagement.
func (mg *LifecycleStageRebootManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this LifecycleStageRebootManagement.
func (mg *LifecycleStageRebootManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this LifecycleStageRebootManagement.
func (mg *LifecycleStageRebootManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this LifecycleStageRebootManagement.
func (mg *LifecycleStageRebootManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this LifecycleStageRebootManagement.
func (mg *LifecycleStageRebootManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this LifecycleStageRebootManagement.
func (mg *LifecycleStageRebootManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this LifecycleStageRebootManagement.
func (mg *LifecycleStageRebootManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstance.
func (mg *ManagedInstance) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstance.
func (mg *ManagedInstance) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstance.
func (mg *ManagedInstance) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstance.
func (mg *ManagedInstance) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstance.
func (mg *ManagedInstance) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstance.
func (mg *ManagedInstance) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstance.
func (mg *ManagedInstance) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstance.
func (mg *ManagedInstance) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceAttachProfileManagement.
func (mg *ManagedInstanceAttachProfileManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceAttachProfileManagement.
func (mg *ManagedInstanceAttachProfileManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceAttachProfileManagement.
func (mg *ManagedInstanceAttachProfileManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceAttachProfileManagement.
func (mg *ManagedInstanceAttachProfileManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceAttachProfileManagement.
func (mg *ManagedInstanceAttachProfileManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceAttachProfileManagement.
func (mg *ManagedInstanceAttachProfileManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceAttachProfileManagement.
func (mg *ManagedInstanceAttachProfileManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceAttachProfileManagement.
func (mg *ManagedInstanceAttachProfileManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceDetachProfileManagement.
func (mg *ManagedInstanceDetachProfileManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceDetachProfileManagement.
func (mg *ManagedInstanceDetachProfileManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceDetachProfileManagement.
func (mg *ManagedInstanceDetachProfileManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceDetachProfileManagement.
func (mg *ManagedInstanceDetachProfileManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceDetachProfileManagement.
func (mg *ManagedInstanceDetachProfileManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceDetachProfileManagement.
func (mg *ManagedInstanceDetachProfileManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceDetachProfileManagement.
func (mg *ManagedInstanceDetachProfileManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceDetachProfileManagement.
func (mg *ManagedInstanceDetachProfileManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceGroup.
func (mg *ManagedInstanceGroup) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceGroup.
func (mg *ManagedInstanceGroup) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceGroup.
func (mg *ManagedInstanceGroup) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceGroup.
func (mg *ManagedInstanceGroup) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceGroup.
func (mg *ManagedInstanceGroup) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceGroup.
func (mg *ManagedInstanceGroup) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceGroup.
func (mg *ManagedInstanceGroup) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceGroup.
func (mg *ManagedInstanceGroup) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceGroupAttachManagedInstancesManagement.
func (mg *ManagedInstanceGroupAttachManagedInstancesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceGroupAttachManagedInstancesManagement.
func (mg *ManagedInstanceGroupAttachManagedInstancesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceGroupAttachManagedInstancesManagement.
func (mg *ManagedInstanceGroupAttachManagedInstancesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceGroupAttachManagedInstancesManagement.
func (mg *ManagedInstanceGroupAttachManagedInstancesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceGroupAttachManagedInstancesManagement.
func (mg *ManagedInstanceGroupAttachManagedInstancesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceGroupAttachManagedInstancesManagement.
func (mg *ManagedInstanceGroupAttachManagedInstancesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceGroupAttachManagedInstancesManagement.
func (mg *ManagedInstanceGroupAttachManagedInstancesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceGroupAttachManagedInstancesManagement.
func (mg *ManagedInstanceGroupAttachManagedInstancesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceGroupAttachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupAttachSoftwareSourcesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceGroupAttachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupAttachSoftwareSourcesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceGroupAttachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupAttachSoftwareSourcesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceGroupAttachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupAttachSoftwareSourcesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceGroupAttachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupAttachSoftwareSourcesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceGroupAttachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupAttachSoftwareSourcesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceGroupAttachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupAttachSoftwareSourcesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceGroupAttachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupAttachSoftwareSourcesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceGroupDetachManagedInstancesManagement.
func (mg *ManagedInstanceGroupDetachManagedInstancesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceGroupDetachManagedInstancesManagement.
func (mg *ManagedInstanceGroupDetachManagedInstancesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceGroupDetachManagedInstancesManagement.
func (mg *ManagedInstanceGroupDetachManagedInstancesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceGroupDetachManagedInstancesManagement.
func (mg *ManagedInstanceGroupDetachManagedInstancesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceGroupDetachManagedInstancesManagement.
func (mg *ManagedInstanceGroupDetachManagedInstancesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceGroupDetachManagedInstancesManagement.
func (mg *ManagedInstanceGroupDetachManagedInstancesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceGroupDetachManagedInstancesManagement.
func (mg *ManagedInstanceGroupDetachManagedInstancesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceGroupDetachManagedInstancesManagement.
func (mg *ManagedInstanceGroupDetachManagedInstancesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceGroupDetachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupDetachSoftwareSourcesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceGroupDetachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupDetachSoftwareSourcesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceGroupDetachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupDetachSoftwareSourcesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceGroupDetachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupDetachSoftwareSourcesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceGroupDetachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupDetachSoftwareSourcesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceGroupDetachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupDetachSoftwareSourcesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceGroupDetachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupDetachSoftwareSourcesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceGroupDetachSoftwareSourcesManagement.
func (mg *ManagedInstanceGroupDetachSoftwareSourcesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceGroupInstallPackagesManagement.
func (mg *ManagedInstanceGroupInstallPackagesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceGroupInstallPackagesManagement.
func (mg *ManagedInstanceGroupInstallPackagesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceGroupInstallPackagesManagement.
func (mg *ManagedInstanceGroupInstallPackagesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceGroupInstallPackagesManagement.
func (mg *ManagedInstanceGroupInstallPackagesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceGroupInstallPackagesManagement.
func (mg *ManagedInstanceGroupInstallPackagesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceGroupInstallPackagesManagement.
func (mg *ManagedInstanceGroupInstallPackagesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceGroupInstallPackagesManagement.
func (mg *ManagedInstanceGroupInstallPackagesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceGroupInstallPackagesManagement.
func (mg *ManagedInstanceGroupInstallPackagesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceGroupInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceGroupInstallWindowsUpdatesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceGroupInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceGroupInstallWindowsUpdatesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceGroupInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceGroupInstallWindowsUpdatesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceGroupInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceGroupInstallWindowsUpdatesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceGroupInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceGroupInstallWindowsUpdatesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceGroupInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceGroupInstallWindowsUpdatesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceGroupInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceGroupInstallWindowsUpdatesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceGroupInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceGroupInstallWindowsUpdatesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceGroupManageModuleStreamsManagement.
func (mg *ManagedInstanceGroupManageModuleStreamsManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceGroupManageModuleStreamsManagement.
func (mg *ManagedInstanceGroupManageModuleStreamsManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceGroupManageModuleStreamsManagement.
func (mg *ManagedInstanceGroupManageModuleStreamsManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceGroupManageModuleStreamsManagement.
func (mg *ManagedInstanceGroupManageModuleStreamsManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceGroupManageModuleStreamsManagement.
func (mg *ManagedInstanceGroupManageModuleStreamsManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceGroupManageModuleStreamsManagement.
func (mg *ManagedInstanceGroupManageModuleStreamsManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceGroupManageModuleStreamsManagement.
func (mg *ManagedInstanceGroupManageModuleStreamsManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceGroupManageModuleStreamsManagement.
func (mg *ManagedInstanceGroupManageModuleStreamsManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceGroupRebootManagement.
func (mg *ManagedInstanceGroupRebootManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceGroupRebootManagement.
func (mg *ManagedInstanceGroupRebootManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceGroupRebootManagement.
func (mg *ManagedInstanceGroupRebootManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceGroupRebootManagement.
func (mg *ManagedInstanceGroupRebootManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceGroupRebootManagement.
func (mg *ManagedInstanceGroupRebootManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceGroupRebootManagement.
func (mg *ManagedInstanceGroupRebootManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceGroupRebootManagement.
func (mg *ManagedInstanceGroupRebootManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceGroupRebootManagement.
func (mg *ManagedInstanceGroupRebootManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceGroupRemovePackagesManagement.
func (mg *ManagedInstanceGroupRemovePackagesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceGroupRemovePackagesManagement.
func (mg *ManagedInstanceGroupRemovePackagesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceGroupRemovePackagesManagement.
func (mg *ManagedInstanceGroupRemovePackagesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceGroupRemovePackagesManagement.
func (mg *ManagedInstanceGroupRemovePackagesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceGroupRemovePackagesManagement.
func (mg *ManagedInstanceGroupRemovePackagesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceGroupRemovePackagesManagement.
func (mg *ManagedInstanceGroupRemovePackagesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceGroupRemovePackagesManagement.
func (mg *ManagedInstanceGroupRemovePackagesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceGroupRemovePackagesManagement.
func (mg *ManagedInstanceGroupRemovePackagesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceGroupUpdateAllPackagesManagement.
func (mg *ManagedInstanceGroupUpdateAllPackagesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceGroupUpdateAllPackagesManagement.
func (mg *ManagedInstanceGroupUpdateAllPackagesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceGroupUpdateAllPackagesManagement.
func (mg *ManagedInstanceGroupUpdateAllPackagesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceGroupUpdateAllPackagesManagement.
func (mg *ManagedInstanceGroupUpdateAllPackagesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceGroupUpdateAllPackagesManagement.
func (mg *ManagedInstanceGroupUpdateAllPackagesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceGroupUpdateAllPackagesManagement.
func (mg *ManagedInstanceGroupUpdateAllPackagesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceGroupUpdateAllPackagesManagement.
func (mg *ManagedInstanceGroupUpdateAllPackagesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceGroupUpdateAllPackagesManagement.
func (mg *ManagedInstanceGroupUpdateAllPackagesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceInstallWindowsUpdatesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceInstallWindowsUpdatesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceInstallWindowsUpdatesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceInstallWindowsUpdatesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceInstallWindowsUpdatesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceInstallWindowsUpdatesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceInstallWindowsUpdatesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceInstallWindowsUpdatesManagement.
func (mg *ManagedInstanceInstallWindowsUpdatesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceRebootManagement.
func (mg *ManagedInstanceRebootManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceRebootManagement.
func (mg *ManagedInstanceRebootManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceRebootManagement.
func (mg *ManagedInstanceRebootManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceRebootManagement.
func (mg *ManagedInstanceRebootManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceRebootManagement.
func (mg *ManagedInstanceRebootManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceRebootManagement.
func (mg *ManagedInstanceRebootManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceRebootManagement.
func (mg *ManagedInstanceRebootManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceRebootManagement.
func (mg *ManagedInstanceRebootManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedInstanceUpdatePackagesManagement.
func (mg *ManagedInstanceUpdatePackagesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagedInstanceUpdatePackagesManagement.
func (mg *ManagedInstanceUpdatePackagesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedInstanceUpdatePackagesManagement.
func (mg *ManagedInstanceUpdatePackagesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedInstanceUpdatePackagesManagement.
func (mg *ManagedInstanceUpdatePackagesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedInstanceUpdatePackagesManagement.
func (mg *ManagedInstanceUpdatePackagesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagedInstanceUpdatePackagesManagement.
func (mg *ManagedInstanceUpdatePackagesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedInstanceUpdatePackagesManagement.
func (mg *ManagedInstanceUpdatePackagesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedInstanceUpdatePackagesManagement.
func (mg *ManagedInstanceUpdatePackagesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagementStation.
func (mg *ManagementStation) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagementStation.
func (mg *ManagementStation) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagementStation.
func (mg *ManagementStation) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagementStation.
func (mg *ManagementStation) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagementStation.
func (mg *ManagementStation) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagementStation.
func (mg *ManagementStation) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagementStation.
func (mg *ManagementStation) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagementStation.
func (mg *ManagementStation) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagementStationAssociateManagedInstancesManagement.
func (mg *ManagementStationAssociateManagedInstancesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagementStationAssociateManagedInstancesManagement.
func (mg *ManagementStationAssociateManagedInstancesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagementStationAssociateManagedInstancesManagement.
func (mg *ManagementStationAssociateManagedInstancesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagementStationAssociateManagedInstancesManagement.
func (mg *ManagementStationAssociateManagedInstancesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagementStationAssociateManagedInstancesManagement.
func (mg *ManagementStationAssociateManagedInstancesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagementStationAssociateManagedInstancesManagement.
func (mg *ManagementStationAssociateManagedInstancesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagementStationAssociateManagedInstancesManagement.
func (mg *ManagementStationAssociateManagedInstancesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagementStationAssociateManagedInstancesManagement.
func (mg *ManagementStationAssociateManagedInstancesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagementStationMirrorSynchronizeManagement.
func (mg *ManagementStationMirrorSynchronizeManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagementStationMirrorSynchronizeManagement.
func (mg *ManagementStationMirrorSynchronizeManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagementStationMirrorSynchronizeManagement.
func (mg *ManagementStationMirrorSynchronizeManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagementStationMirrorSynchronizeManagement.
func (mg *ManagementStationMirrorSynchronizeManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagementStationMirrorSynchronizeManagement.
func (mg *ManagementStationMirrorSynchronizeManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagementStationMirrorSynchronizeManagement.
func (mg *ManagementStationMirrorSynchronizeManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagementStationMirrorSynchronizeManagement.
func (mg *ManagementStationMirrorSynchronizeManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagementStationMirrorSynchronizeManagement.
func (mg *ManagementStationMirrorSynchronizeManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagementStationRefreshManagement.
func (mg *ManagementStationRefreshManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagementStationRefreshManagement.
func (mg *ManagementStationRefreshManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagementStationRefreshManagement.
func (mg *ManagementStationRefreshManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagementStationRefreshManagement.
func (mg *ManagementStationRefreshManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagementStationRefreshManagement.
func (mg *ManagementStationRefreshManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagementStationRefreshManagement.
func (mg *ManagementStationRefreshManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagementStationRefreshManagement.
func (mg *ManagementStationRefreshManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagementStationRefreshManagement.
func (mg *ManagementStationRefreshManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagementStationSynchronizeMirrorsManagement.
func (mg *ManagementStationSynchronizeMirrorsManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ManagementStationSynchronizeMirrorsManagement.
func (mg *ManagementStationSynchronizeMirrorsManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagementStationSynchronizeMirrorsManagement.
func (mg *ManagementStationSynchronizeMirrorsManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagementStationSynchronizeMirrorsManagement.
func (mg *ManagementStationSynchronizeMirrorsManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagementStationSynchronizeMirrorsManagement.
func (mg *ManagementStationSynchronizeMirrorsManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ManagementStationSynchronizeMirrorsManagement.
func (mg *ManagementStationSynchronizeMirrorsManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagementStationSynchronizeMirrorsManagement.
func (mg *ManagementStationSynchronizeMirrorsManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagementStationSynchronizeMirrorsManagement.
func (mg *ManagementStationSynchronizeMirrorsManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this Profile.
func (mg *Profile) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this Profile.
func (mg *Profile) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this Profile.
func (mg *Profile) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this Profile.
func (mg *Profile) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this Profile.
func (mg *Profile) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this Profile.
func (mg *Profile) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this Profile.
func (mg *Profile) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this Profile.
func (mg *Profile) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ProfileAttachLifecycleStageManagement.
func (mg *ProfileAttachLifecycleStageManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ProfileAttachLifecycleStageManagement.
func (mg *ProfileAttachLifecycleStageManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ProfileAttachLifecycleStageManagement.
func (mg *ProfileAttachLifecycleStageManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ProfileAttachLifecycleStageManagement.
func (mg *ProfileAttachLifecycleStageManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ProfileAttachLifecycleStageManagement.
func (mg *ProfileAttachLifecycleStageManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ProfileAttachLifecycleStageManagement.
func (mg *ProfileAttachLifecycleStageManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ProfileAttachLifecycleStageManagement.
func (mg *ProfileAttachLifecycleStageManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ProfileAttachLifecycleStageManagement.
func (mg *ProfileAttachLifecycleStageManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ProfileAttachManagedInstanceGroupManagement.
func (mg *ProfileAttachManagedInstanceGroupManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ProfileAttachManagedInstanceGroupManagement.
func (mg *ProfileAttachManagedInstanceGroupManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ProfileAttachManagedInstanceGroupManagement.
func (mg *ProfileAttachManagedInstanceGroupManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ProfileAttachManagedInstanceGroupManagement.
func (mg *ProfileAttachManagedInstanceGroupManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ProfileAttachManagedInstanceGroupManagement.
func (mg *ProfileAttachManagedInstanceGroupManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ProfileAttachManagedInstanceGroupManagement.
func (mg *ProfileAttachManagedInstanceGroupManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ProfileAttachManagedInstanceGroupManagement.
func (mg *ProfileAttachManagedInstanceGroupManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ProfileAttachManagedInstanceGroupManagement.
func (mg *ProfileAttachManagedInstanceGroupManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ProfileAttachManagementStationManagement.
func (mg *ProfileAttachManagementStationManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ProfileAttachManagementStationManagement.
func (mg *ProfileAttachManagementStationManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ProfileAttachManagementStationManagement.
func (mg *ProfileAttachManagementStationManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ProfileAttachManagementStationManagement.
func (mg *ProfileAttachManagementStationManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ProfileAttachManagementStationManagement.
func (mg *ProfileAttachManagementStationManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ProfileAttachManagementStationManagement.
func (mg *ProfileAttachManagementStationManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ProfileAttachManagementStationManagement.
func (mg *ProfileAttachManagementStationManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ProfileAttachManagementStationManagement.
func (mg *ProfileAttachManagementStationManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ProfileAttachSoftwareSourcesManagement.
func (mg *ProfileAttachSoftwareSourcesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ProfileAttachSoftwareSourcesManagement.
func (mg *ProfileAttachSoftwareSourcesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ProfileAttachSoftwareSourcesManagement.
func (mg *ProfileAttachSoftwareSourcesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ProfileAttachSoftwareSourcesManagement.
func (mg *ProfileAttachSoftwareSourcesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ProfileAttachSoftwareSourcesManagement.
func (mg *ProfileAttachSoftwareSourcesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ProfileAttachSoftwareSourcesManagement.
func (mg *ProfileAttachSoftwareSourcesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ProfileAttachSoftwareSourcesManagement.
func (mg *ProfileAttachSoftwareSourcesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ProfileAttachSoftwareSourcesManagement.
func (mg *ProfileAttachSoftwareSourcesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ProfileDetachSoftwareSourcesManagement.
func (mg *ProfileDetachSoftwareSourcesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ProfileDetachSoftwareSourcesManagement.
func (mg *ProfileDetachSoftwareSourcesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ProfileDetachSoftwareSourcesManagement.
func (mg *ProfileDetachSoftwareSourcesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ProfileDetachSoftwareSourcesManagement.
func (mg *ProfileDetachSoftwareSourcesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ProfileDetachSoftwareSourcesManagement.
func (mg *ProfileDetachSoftwareSourcesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ProfileDetachSoftwareSourcesManagement.
func (mg *ProfileDetachSoftwareSourcesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ProfileDetachSoftwareSourcesManagement.
func (mg *ProfileDetachSoftwareSourcesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ProfileDetachSoftwareSourcesManagement.
func (mg *ProfileDetachSoftwareSourcesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ScheduledJob.
func (mg *ScheduledJob) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ScheduledJob.
func (mg *ScheduledJob) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ScheduledJob.
func (mg *ScheduledJob) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ScheduledJob.
func (mg *ScheduledJob) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ScheduledJob.
func (mg *ScheduledJob) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ScheduledJob.
func (mg *ScheduledJob) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ScheduledJob.
func (mg *ScheduledJob) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ScheduledJob.
func (mg *ScheduledJob) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SoftwareSource.
func (mg *SoftwareSource) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this SoftwareSource.
func (mg *SoftwareSource) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SoftwareSource.
func (mg *SoftwareSource) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SoftwareSource.
func (mg *SoftwareSource) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SoftwareSource.
func (mg *SoftwareSource) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this SoftwareSource.
func (mg *SoftwareSource) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SoftwareSource.
func (mg *SoftwareSource) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SoftwareSource.
func (mg *SoftwareSource) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SoftwareSourceAddPackagesManagement.
func (mg *SoftwareSourceAddPackagesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this SoftwareSourceAddPackagesManagement.
func (mg *SoftwareSourceAddPackagesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SoftwareSourceAddPackagesManagement.
func (mg *SoftwareSourceAddPackagesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SoftwareSourceAddPackagesManagement.
func (mg *SoftwareSourceAddPackagesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SoftwareSourceAddPackagesManagement.
func (mg *SoftwareSourceAddPackagesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this SoftwareSourceAddPackagesManagement.
func (mg *SoftwareSourceAddPackagesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SoftwareSourceAddPackagesManagement.
func (mg *SoftwareSourceAddPackagesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SoftwareSourceAddPackagesManagement.
func (mg *SoftwareSourceAddPackagesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SoftwareSourceChangeAvailabilityManagement.
func (mg *SoftwareSourceChangeAvailabilityManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this SoftwareSourceChangeAvailabilityManagement.
func (mg *SoftwareSourceChangeAvailabilityManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SoftwareSourceChangeAvailabilityManagement.
func (mg *SoftwareSourceChangeAvailabilityManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SoftwareSourceChangeAvailabilityManagement.
func (mg *SoftwareSourceChangeAvailabilityManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SoftwareSourceChangeAvailabilityManagement.
func (mg *SoftwareSourceChangeAvailabilityManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this SoftwareSourceChangeAvailabilityManagement.
func (mg *SoftwareSourceChangeAvailabilityManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SoftwareSourceChangeAvailabilityManagement.
func (mg *SoftwareSourceChangeAvailabilityManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SoftwareSourceChangeAvailabilityManagement.
func (mg *SoftwareSourceChangeAvailabilityManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SoftwareSourceGenerateMetadataManagement.
func (mg *SoftwareSourceGenerateMetadataManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this SoftwareSourceGenerateMetadataManagement.
func (mg *SoftwareSourceGenerateMetadataManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SoftwareSourceGenerateMetadataManagement.
func (mg *SoftwareSourceGenerateMetadataManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SoftwareSourceGenerateMetadataManagement.
func (mg *SoftwareSourceGenerateMetadataManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SoftwareSourceGenerateMetadataManagement.
func (mg *SoftwareSourceGenerateMetadataManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this SoftwareSourceGenerateMetadataManagement.
func (mg *SoftwareSourceGenerateMetadataManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SoftwareSourceGenerateMetadataManagement.
func (mg *SoftwareSourceGenerateMetadataManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SoftwareSourceGenerateMetadataManagement.
func (mg *SoftwareSourceGenerateMetadataManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SoftwareSourceManifest.
func (mg *SoftwareSourceManifest) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this SoftwareSourceManifest.
func (mg *SoftwareSourceManifest) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SoftwareSourceManifest.
func (mg *SoftwareSourceManifest) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SoftwareSourceManifest.
func (mg *SoftwareSourceManifest) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SoftwareSourceManifest.
func (mg *SoftwareSourceManifest) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this SoftwareSourceManifest.
func (mg *SoftwareSourceManifest) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SoftwareSourceManifest.
func (mg *SoftwareSourceManifest) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SoftwareSourceManifest.
func (mg *SoftwareSourceManifest) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SoftwareSourceRemovePackagesManagement.
func (mg *SoftwareSourceRemovePackagesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this SoftwareSourceRemovePackagesManagement.
func (mg *SoftwareSourceRemovePackagesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SoftwareSourceRemovePackagesManagement.
func (mg *SoftwareSourceRemovePackagesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SoftwareSourceRemovePackagesManagement.
func (mg *SoftwareSourceRemovePackagesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SoftwareSourceRemovePackagesManagement.
func (mg *SoftwareSourceRemovePackagesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this SoftwareSourceRemovePackagesManagement.
func (mg *SoftwareSourceRemovePackagesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SoftwareSourceRemovePackagesManagement.
func (mg *SoftwareSourceRemovePackagesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SoftwareSourceRemovePackagesManagement.
func (mg *SoftwareSourceRemovePackagesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this SoftwareSourceReplacePackagesManagement.
func (mg *SoftwareSourceReplacePackagesManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this SoftwareSourceReplacePackagesManagement.
func (mg *SoftwareSourceReplacePackagesManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SoftwareSourceReplacePackagesManagement.
func (mg *SoftwareSourceReplacePackagesManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SoftwareSourceReplacePackagesManagement.
func (mg *SoftwareSourceReplacePackagesManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this SoftwareSourceReplacePackagesManagement.
func (mg *SoftwareSourceReplacePackagesManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this SoftwareSourceReplacePackagesManagement.
func (mg *SoftwareSourceReplacePackagesManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SoftwareSourceReplacePackagesManagement.
func (mg *SoftwareSourceReplacePackagesManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this SoftwareSourceReplacePackagesManagement.
func (mg *SoftwareSourceReplacePackagesManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this WorkRequestRerunManagement.
func (mg *WorkRequestRerunManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this WorkRequestRerunManagement.
func (mg *WorkRequestRerunManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this WorkRequestRerunManagement.
func (mg *WorkRequestRerunManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this WorkRequestRerunManagement.
func (mg *WorkRequestRerunManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this WorkRequestRerunManagement.
func (mg *WorkRequestRerunManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this WorkRequestRerunManagement.
func (mg *WorkRequestRerunManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this WorkRequestRerunManagement.
func (mg *WorkRequestRerunManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this WorkRequestRerunManagement.
func (mg *WorkRequestRerunManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
