/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SoftwareSourceRemovePackagesManagementInitParameters struct {

	// List of packages specified by the name of the package (N) or the full package name (NVRA or NEVRA).
	Packages []*string `json:"packages,omitempty" tf:"packages,omitempty"`

	// The OCID of the software source.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/osmanagementhub/v1alpha1.SoftwareSource
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	SoftwareSourceID *string `json:"softwareSourceId,omitempty" tf:"software_source_id,omitempty"`

	// Reference to a SoftwareSource in osmanagementhub to populate softwareSourceId.
	// +kubebuilder:validation:Optional
	SoftwareSourceIDRef *v1.NamespacedReference `json:"softwareSourceIdRef,omitempty" tf:"-"`

	// Selector for a SoftwareSource in osmanagementhub to populate softwareSourceId.
	// +kubebuilder:validation:Optional
	SoftwareSourceIDSelector *v1.NamespacedSelector `json:"softwareSourceIdSelector,omitempty" tf:"-"`
}

type SoftwareSourceRemovePackagesManagementObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of packages specified by the name of the package (N) or the full package name (NVRA or NEVRA).
	Packages []*string `json:"packages,omitempty" tf:"packages,omitempty"`

	// The OCID of the software source.
	SoftwareSourceID *string `json:"softwareSourceId,omitempty" tf:"software_source_id,omitempty"`
}

type SoftwareSourceRemovePackagesManagementParameters struct {

	// List of packages specified by the name of the package (N) or the full package name (NVRA or NEVRA).
	// +kubebuilder:validation:Optional
	Packages []*string `json:"packages,omitempty" tf:"packages,omitempty"`

	// The OCID of the software source.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/osmanagementhub/v1alpha1.SoftwareSource
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	SoftwareSourceID *string `json:"softwareSourceId,omitempty" tf:"software_source_id,omitempty"`

	// Reference to a SoftwareSource in osmanagementhub to populate softwareSourceId.
	// +kubebuilder:validation:Optional
	SoftwareSourceIDRef *v1.NamespacedReference `json:"softwareSourceIdRef,omitempty" tf:"-"`

	// Selector for a SoftwareSource in osmanagementhub to populate softwareSourceId.
	// +kubebuilder:validation:Optional
	SoftwareSourceIDSelector *v1.NamespacedSelector `json:"softwareSourceIdSelector,omitempty" tf:"-"`
}

// SoftwareSourceRemovePackagesManagementSpec defines the desired state of SoftwareSourceRemovePackagesManagement
type SoftwareSourceRemovePackagesManagementSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SoftwareSourceRemovePackagesManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SoftwareSourceRemovePackagesManagementInitParameters `json:"initProvider,omitempty"`
}

// SoftwareSourceRemovePackagesManagementStatus defines the observed state of SoftwareSourceRemovePackagesManagement.
type SoftwareSourceRemovePackagesManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SoftwareSourceRemovePackagesManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SoftwareSourceRemovePackagesManagement is the Schema for the SoftwareSourceRemovePackagesManagements API. Provides the Software Source Remove Packages Management resource in Oracle Cloud Infrastructure Os Management Hub service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type SoftwareSourceRemovePackagesManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.packages) || (has(self.initProvider) && has(self.initProvider.packages))",message="spec.forProvider.packages is a required parameter"
	Spec   SoftwareSourceRemovePackagesManagementSpec   `json:"spec"`
	Status SoftwareSourceRemovePackagesManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SoftwareSourceRemovePackagesManagementList contains a list of SoftwareSourceRemovePackagesManagements
type SoftwareSourceRemovePackagesManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SoftwareSourceRemovePackagesManagement `json:"items"`
}

// Repository type metadata.
var (
	SoftwareSourceRemovePackagesManagement_Kind             = "SoftwareSourceRemovePackagesManagement"
	SoftwareSourceRemovePackagesManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SoftwareSourceRemovePackagesManagement_Kind}.String()
	SoftwareSourceRemovePackagesManagement_KindAPIVersion   = SoftwareSourceRemovePackagesManagement_Kind + "." + CRDGroupVersion.String()
	SoftwareSourceRemovePackagesManagement_GroupVersionKind = CRDGroupVersion.WithKind(SoftwareSourceRemovePackagesManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&SoftwareSourceRemovePackagesManagement{}, &SoftwareSourceRemovePackagesManagementList{})
}
