/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type IndexInitParameters struct {

	// The OCID of the table's compartment.  Required if the tableNameOrId path parameter is a table name. Optional if tableNameOrId is an OCID.  If tableNameOrId is an OCID, and compartmentId is supplied, the latter must match the identified table's compartmentId.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// If true, the operation completes successfully even when the index exists.  Otherwise, an attempt to create an index that already exists will return an error.
	IsIfNotExists *bool `json:"isIfNotExists,omitempty" tf:"is_if_not_exists,omitempty"`

	// A set of keys for a secondary index.
	Keys []KeysInitParameters `json:"keys,omitempty" tf:"keys,omitempty"`

	// Index name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A table name within the compartment, or a table OCID.
	TableNameOrID *string `json:"tableNameOrId,omitempty" tf:"table_name_or_id,omitempty"`
}

type IndexObservation struct {

	// The OCID of the table's compartment.  Required if the tableNameOrId path parameter is a table name. Optional if tableNameOrId is an OCID.  If tableNameOrId is an OCID, and compartmentId is supplied, the latter must match the identified table's compartmentId.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// If true, the operation completes successfully even when the index exists.  Otherwise, an attempt to create an index that already exists will return an error.
	IsIfNotExists *bool `json:"isIfNotExists,omitempty" tf:"is_if_not_exists,omitempty"`

	// A set of keys for a secondary index.
	Keys []KeysObservation `json:"keys,omitempty" tf:"keys,omitempty"`

	// A message describing the current state in more detail.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// Index name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The state of an index.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// the OCID of the table to which this index belongs.
	TableID *string `json:"tableId,omitempty" tf:"table_id,omitempty"`

	// The name of the table to which this index belongs.
	TableName *string `json:"tableName,omitempty" tf:"table_name,omitempty"`

	// A table name within the compartment, or a table OCID.
	TableNameOrID *string `json:"tableNameOrId,omitempty" tf:"table_name_or_id,omitempty"`
}

type IndexParameters struct {

	// The OCID of the table's compartment.  Required if the tableNameOrId path parameter is a table name. Optional if tableNameOrId is an OCID.  If tableNameOrId is an OCID, and compartmentId is supplied, the latter must match the identified table's compartmentId.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// If true, the operation completes successfully even when the index exists.  Otherwise, an attempt to create an index that already exists will return an error.
	// +kubebuilder:validation:Optional
	IsIfNotExists *bool `json:"isIfNotExists,omitempty" tf:"is_if_not_exists,omitempty"`

	// A set of keys for a secondary index.
	// +kubebuilder:validation:Optional
	Keys []KeysParameters `json:"keys,omitempty" tf:"keys,omitempty"`

	// Index name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A table name within the compartment, or a table OCID.
	// +kubebuilder:validation:Optional
	TableNameOrID *string `json:"tableNameOrId,omitempty" tf:"table_name_or_id,omitempty"`
}

type KeysInitParameters struct {

	// The name of a column to be included as an index key.
	ColumnName *string `json:"columnName,omitempty" tf:"column_name,omitempty"`

	// If the specified column is of type JSON, jsonFieldType contains the type of the field indicated by jsonPath.
	JSONFieldType *string `json:"jsonFieldType,omitempty" tf:"json_field_type,omitempty"`

	// If the specified column is of type JSON, jsonPath contains a dotted path indicating the field within the JSON object that will be the index key.
	JSONPath *string `json:"jsonPath,omitempty" tf:"json_path,omitempty"`
}

type KeysObservation struct {

	// The name of a column to be included as an index key.
	ColumnName *string `json:"columnName,omitempty" tf:"column_name,omitempty"`

	// If the specified column is of type JSON, jsonFieldType contains the type of the field indicated by jsonPath.
	JSONFieldType *string `json:"jsonFieldType,omitempty" tf:"json_field_type,omitempty"`

	// If the specified column is of type JSON, jsonPath contains a dotted path indicating the field within the JSON object that will be the index key.
	JSONPath *string `json:"jsonPath,omitempty" tf:"json_path,omitempty"`
}

type KeysParameters struct {

	// The name of a column to be included as an index key.
	// +kubebuilder:validation:Optional
	ColumnName *string `json:"columnName" tf:"column_name,omitempty"`

	// If the specified column is of type JSON, jsonFieldType contains the type of the field indicated by jsonPath.
	// +kubebuilder:validation:Optional
	JSONFieldType *string `json:"jsonFieldType,omitempty" tf:"json_field_type,omitempty"`

	// If the specified column is of type JSON, jsonPath contains a dotted path indicating the field within the JSON object that will be the index key.
	// +kubebuilder:validation:Optional
	JSONPath *string `json:"jsonPath,omitempty" tf:"json_path,omitempty"`
}

// IndexSpec defines the desired state of Index
type IndexSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IndexParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IndexInitParameters `json:"initProvider,omitempty"`
}

// IndexStatus defines the observed state of Index.
type IndexStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IndexObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Index is the Schema for the Indexs API. Provides the Index resource in Oracle Cloud Infrastructure NoSQL Database service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type Index struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.keys) || (has(self.initProvider) && has(self.initProvider.keys))",message="spec.forProvider.keys is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tableNameOrId) || (has(self.initProvider) && has(self.initProvider.tableNameOrId))",message="spec.forProvider.tableNameOrId is a required parameter"
	Spec   IndexSpec   `json:"spec"`
	Status IndexStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IndexList contains a list of Indexs
type IndexList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Index `json:"items"`
}

// Repository type metadata.
var (
	Index_Kind             = "Index"
	Index_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Index_Kind}.String()
	Index_KindAPIVersion   = Index_Kind + "." + CRDGroupVersion.String()
	Index_GroupVersionKind = CRDGroupVersion.WithKind(Index_Kind)
)

func init() {
	SchemeBuilder.Register(&Index{}, &IndexList{})
}
