apiVersion: loadbalancer.oci.upbound.io/v1alpha1
kind: Listener
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: lb-listener1
  name: lb-listener1
spec:
  forProvider:
    connectionConfiguration:
    - idleTimeoutInSeconds: "2"
    defaultBackendSetNameSelector:
      matchLabels:
        testing.upbound.io/example-name: lb-bes1
    hostnameNamesRefs:
    - name: test_hostname1
    - name: test_hostname2
    loadBalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: lb1
    name: http
    port: 80
    protocol: HTTP
    ruleSetNamesRefs:
    - name: test_rule_set

---

apiVersion: networking.oci.upbound.io/v1alpha1
kind: InternetGateway
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: internetgateway1
  name: internetgateway1
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    displayName: internetgateway1
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn1

---

apiVersion: networking.oci.upbound.io/v1alpha1
kind: PublicIp
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: test_reserved_ip
  name: test-reserved-ip
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    lifetime: RESERVED

---

apiVersion: networking.oci.upbound.io/v1alpha1
kind: RouteTable
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: routetable1
  name: routetable1
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    displayName: routetable1
    routeRules:
    - destination: 0.0.0.0/0
      destinationType: CIDR_BLOCK
      networkEntityIdSelector:
        matchLabels:
          testing.upbound.io/example-name: internetgateway1
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn1

---

apiVersion: networking.oci.upbound.io/v1alpha1
kind: SecurityList
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: securitylist1
  name: securitylist1
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn1
    displayName: public
    egressSecurityRules:
    - destination: 0.0.0.0/0
      protocol: all
    ingressSecurityRules:
    - protocol: "6"
      source: 0.0.0.0/0
      tcpOptions:
      - max: 80
        min: 80
    - protocol: "6"
      source: 0.0.0.0/0
      tcpOptions:
      - max: 443
        min: 443
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn1

---

apiVersion: networking.oci.upbound.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: subnet1
  name: subnet1
spec:
  forProvider:
    availabilityDomain: ${data.oci_identity_availability_domain.ad1.name}
    cidrBlock: 10.1.20.0/24
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    dhcpOptionsIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn1
    displayName: subnet1
    dnsLabel: subnet1
    provisioner:
      local-exec:
      - command: sleep 5
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: routetable1
    securityListIdRefs:
    - name: securitylist1
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn1

---

apiVersion: networking.oci.upbound.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: subnet2
  name: subnet2
spec:
  forProvider:
    availabilityDomain: ${data.oci_identity_availability_domain.ad2.name}
    cidrBlock: 10.1.21.0/24
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    dhcpOptionsIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn1
    displayName: subnet2
    dnsLabel: subnet2
    provisioner:
      local-exec:
      - command: sleep 5
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: routetable1
    securityListIdRefs:
    - name: securitylist1
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn1

---

apiVersion: networking.oci.upbound.io/v1alpha1
kind: Vcn
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: vcn1
  name: vcn1
spec:
  forProvider:
    cidrBlock: 10.1.0.0/16
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    displayName: vcn1
    dnsLabel: vcn1

---

apiVersion: loadbalancer.oci.upbound.io/v1alpha1
kind: BackendSet
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: lb-bes1
  name: lb-bes1
spec:
  forProvider:
    backendMaxConnections: "1000"
    healthChecker:
    - port: "80"
      protocol: HTTP
      responseBodyRegex: .*
      urlPath: /
    loadBalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: lb1
    name: lb-bes1
    policy: ROUND_ROBIN
