//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImport) DeepCopyInto(out *ManagementDashboardsImport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImport.
func (in *ManagementDashboardsImport) DeepCopy() *ManagementDashboardsImport {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementDashboardsImport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImportInitParameters) DeepCopyInto(out *ManagementDashboardsImportInitParameters) {
	*out = *in
	if in.ImportDetails != nil {
		in, out := &in.ImportDetails, &out.ImportDetails
		*out = new(string)
		**out = **in
	}
	if in.ImportDetailsFile != nil {
		in, out := &in.ImportDetailsFile, &out.ImportDetailsFile
		*out = new(string)
		**out = **in
	}
	if in.OverrideDashboardCompartmentOcid != nil {
		in, out := &in.OverrideDashboardCompartmentOcid, &out.OverrideDashboardCompartmentOcid
		*out = new(string)
		**out = **in
	}
	if in.OverrideSameName != nil {
		in, out := &in.OverrideSameName, &out.OverrideSameName
		*out = new(string)
		**out = **in
	}
	if in.OverrideSavedSearchCompartmentOcid != nil {
		in, out := &in.OverrideSavedSearchCompartmentOcid, &out.OverrideSavedSearchCompartmentOcid
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImportInitParameters.
func (in *ManagementDashboardsImportInitParameters) DeepCopy() *ManagementDashboardsImportInitParameters {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImportInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImportList) DeepCopyInto(out *ManagementDashboardsImportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagementDashboardsImport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImportList.
func (in *ManagementDashboardsImportList) DeepCopy() *ManagementDashboardsImportList {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementDashboardsImportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImportObservation) DeepCopyInto(out *ManagementDashboardsImportObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ImportDetails != nil {
		in, out := &in.ImportDetails, &out.ImportDetails
		*out = new(string)
		**out = **in
	}
	if in.ImportDetailsFile != nil {
		in, out := &in.ImportDetailsFile, &out.ImportDetailsFile
		*out = new(string)
		**out = **in
	}
	if in.OverrideDashboardCompartmentOcid != nil {
		in, out := &in.OverrideDashboardCompartmentOcid, &out.OverrideDashboardCompartmentOcid
		*out = new(string)
		**out = **in
	}
	if in.OverrideSameName != nil {
		in, out := &in.OverrideSameName, &out.OverrideSameName
		*out = new(string)
		**out = **in
	}
	if in.OverrideSavedSearchCompartmentOcid != nil {
		in, out := &in.OverrideSavedSearchCompartmentOcid, &out.OverrideSavedSearchCompartmentOcid
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImportObservation.
func (in *ManagementDashboardsImportObservation) DeepCopy() *ManagementDashboardsImportObservation {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImportObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImportParameters) DeepCopyInto(out *ManagementDashboardsImportParameters) {
	*out = *in
	if in.ImportDetails != nil {
		in, out := &in.ImportDetails, &out.ImportDetails
		*out = new(string)
		**out = **in
	}
	if in.ImportDetailsFile != nil {
		in, out := &in.ImportDetailsFile, &out.ImportDetailsFile
		*out = new(string)
		**out = **in
	}
	if in.OverrideDashboardCompartmentOcid != nil {
		in, out := &in.OverrideDashboardCompartmentOcid, &out.OverrideDashboardCompartmentOcid
		*out = new(string)
		**out = **in
	}
	if in.OverrideSameName != nil {
		in, out := &in.OverrideSameName, &out.OverrideSameName
		*out = new(string)
		**out = **in
	}
	if in.OverrideSavedSearchCompartmentOcid != nil {
		in, out := &in.OverrideSavedSearchCompartmentOcid, &out.OverrideSavedSearchCompartmentOcid
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImportParameters.
func (in *ManagementDashboardsImportParameters) DeepCopy() *ManagementDashboardsImportParameters {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImportParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImportSpec) DeepCopyInto(out *ManagementDashboardsImportSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImportSpec.
func (in *ManagementDashboardsImportSpec) DeepCopy() *ManagementDashboardsImportSpec {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImportStatus) DeepCopyInto(out *ManagementDashboardsImportStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImportStatus.
func (in *ManagementDashboardsImportStatus) DeepCopy() *ManagementDashboardsImportStatus {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImportStatus)
	in.DeepCopyInto(out)
	return out
}
