/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type UnsetUserAssessmentBaselineManagementInitParameters struct {

	// The compartment OCID where the assessment resides.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// The OCID of the user assessment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/datasafe/v1alpha1.SetUserAssessmentBaselineManagement
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("user_assessment_id",true)
	UserAssessmentID *string `json:"userAssessmentId,omitempty" tf:"user_assessment_id,omitempty"`

	// Reference to a SetUserAssessmentBaselineManagement in datasafe to populate userAssessmentId.
	// +kubebuilder:validation:Optional
	UserAssessmentIDRef *v1.NamespacedReference `json:"userAssessmentIdRef,omitempty" tf:"-"`

	// Selector for a SetUserAssessmentBaselineManagement in datasafe to populate userAssessmentId.
	// +kubebuilder:validation:Optional
	UserAssessmentIDSelector *v1.NamespacedSelector `json:"userAssessmentIdSelector,omitempty" tf:"-"`
}

type UnsetUserAssessmentBaselineManagementObservation struct {

	// The compartment OCID where the assessment resides.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the user assessment.
	UserAssessmentID *string `json:"userAssessmentId,omitempty" tf:"user_assessment_id,omitempty"`
}

type UnsetUserAssessmentBaselineManagementParameters struct {

	// The compartment OCID where the assessment resides.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// The OCID of the user assessment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/datasafe/v1alpha1.SetUserAssessmentBaselineManagement
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("user_assessment_id",true)
	// +kubebuilder:validation:Optional
	UserAssessmentID *string `json:"userAssessmentId,omitempty" tf:"user_assessment_id,omitempty"`

	// Reference to a SetUserAssessmentBaselineManagement in datasafe to populate userAssessmentId.
	// +kubebuilder:validation:Optional
	UserAssessmentIDRef *v1.NamespacedReference `json:"userAssessmentIdRef,omitempty" tf:"-"`

	// Selector for a SetUserAssessmentBaselineManagement in datasafe to populate userAssessmentId.
	// +kubebuilder:validation:Optional
	UserAssessmentIDSelector *v1.NamespacedSelector `json:"userAssessmentIdSelector,omitempty" tf:"-"`
}

// UnsetUserAssessmentBaselineManagementSpec defines the desired state of UnsetUserAssessmentBaselineManagement
type UnsetUserAssessmentBaselineManagementSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UnsetUserAssessmentBaselineManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UnsetUserAssessmentBaselineManagementInitParameters `json:"initProvider,omitempty"`
}

// UnsetUserAssessmentBaselineManagementStatus defines the observed state of UnsetUserAssessmentBaselineManagement.
type UnsetUserAssessmentBaselineManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UnsetUserAssessmentBaselineManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UnsetUserAssessmentBaselineManagement is the Schema for the UnsetUserAssessmentBaselineManagements API. Provides the Unset User Assessment Baseline Management resource in Oracle Cloud Infrastructure Data Safe service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type UnsetUserAssessmentBaselineManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UnsetUserAssessmentBaselineManagementSpec   `json:"spec"`
	Status            UnsetUserAssessmentBaselineManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UnsetUserAssessmentBaselineManagementList contains a list of UnsetUserAssessmentBaselineManagements
type UnsetUserAssessmentBaselineManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UnsetUserAssessmentBaselineManagement `json:"items"`
}

// Repository type metadata.
var (
	UnsetUserAssessmentBaselineManagement_Kind             = "UnsetUserAssessmentBaselineManagement"
	UnsetUserAssessmentBaselineManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UnsetUserAssessmentBaselineManagement_Kind}.String()
	UnsetUserAssessmentBaselineManagement_KindAPIVersion   = UnsetUserAssessmentBaselineManagement_Kind + "." + CRDGroupVersion.String()
	UnsetUserAssessmentBaselineManagement_GroupVersionKind = CRDGroupVersion.WithKind(UnsetUserAssessmentBaselineManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&UnsetUserAssessmentBaselineManagement{}, &UnsetUserAssessmentBaselineManagementList{})
}
