/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DeploymentBackupInitParameters struct {

	// Name of the bucket where the object is to be uploaded in the object storage
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Updatable) The OCID of the compartment being referenced.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Tags defined for this resource. Each key is predefined and scoped to a namespace.  Example: {"foo-namespace.bar-key": "value"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// The OCID of the deployment being referenced.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/goldengate/v1alpha1.Deployment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DeploymentID *string `json:"deploymentId,omitempty" tf:"deployment_id,omitempty"`

	// Reference to a Deployment in goldengate to populate deploymentId.
	// +kubebuilder:validation:Optional
	DeploymentIDRef *v1.Reference `json:"deploymentIdRef,omitempty" tf:"-"`

	// Selector for a Deployment in goldengate to populate deploymentId.
	// +kubebuilder:validation:Optional
	DeploymentIDSelector *v1.Selector `json:"deploymentIdSelector,omitempty" tf:"-"`

	// An object's Display Name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) A simple key-value pair that is applied without any predefined name, type, or scope. Exists for cross-compatibility only.  Example: {"bar-key": "value"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	IsLockOverride *bool `json:"isLockOverride,omitempty" tf:"is_lock_override,omitempty"`

	// Parameter to allow users to create backup without trails
	IsMetadataOnly *bool `json:"isMetadataOnly,omitempty" tf:"is_metadata_only,omitempty"`

	// Locks associated with this resource.
	Locks []DeploymentBackupLocksInitParameters `json:"locks,omitempty" tf:"locks,omitempty"`

	// Name of namespace that serves as a container for all of your buckets
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Name of the object to be uploaded to object storage
	Object *string `json:"object,omitempty" tf:"object,omitempty"`
}

type DeploymentBackupLocksInitParameters struct {

	// A message added by the creator of the lock. This is typically used to give an indication of why the resource is locked.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// Type of the lock.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DeploymentBackupLocksObservation struct {

	// A message added by the creator of the lock. This is typically used to give an indication of why the resource is locked.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// The id of the resource that is locking this resource. Indicates that deleting this resource will remove the lock.
	RelatedResourceID *string `json:"relatedResourceId,omitempty" tf:"related_resource_id,omitempty"`

	// When the lock was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// Type of the lock.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DeploymentBackupLocksParameters struct {

	// A message added by the creator of the lock. This is typically used to give an indication of why the resource is locked.
	// +kubebuilder:validation:Optional
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// Type of the lock.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type DeploymentBackupObservation struct {

	// Possible deployment backup source types.
	BackupSourceType *string `json:"backupSourceType,omitempty" tf:"backup_source_type,omitempty"`

	// Possible Deployment backup types.
	BackupType *string `json:"backupType,omitempty" tf:"backup_type,omitempty"`

	// Name of the bucket where the object is to be uploaded in the object storage
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Updatable) The OCID of the compartment being referenced.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Tags defined for this resource. Each key is predefined and scoped to a namespace.  Example: {"foo-namespace.bar-key": "value"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// The OCID of the deployment being referenced.
	DeploymentID *string `json:"deploymentId,omitempty" tf:"deployment_id,omitempty"`

	// The type of deployment, which can be any one of the Allowed values.  NOTE: Use of the value 'OGG' is maintained for backward compatibility purposes.  Its use is discouraged in favor of 'DATABASE_ORACLE'.
	DeploymentType *string `json:"deploymentType,omitempty" tf:"deployment_type,omitempty"`

	// An object's Display Name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) A simple key-value pair that is applied without any predefined name, type, or scope. Exists for cross-compatibility only.  Example: {"bar-key": "value"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the backup being referenced.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// True if this object is automatically created
	IsAutomatic *bool `json:"isAutomatic,omitempty" tf:"is_automatic,omitempty"`

	IsLockOverride *bool `json:"isLockOverride,omitempty" tf:"is_lock_override,omitempty"`

	// Parameter to allow users to create backup without trails
	IsMetadataOnly *bool `json:"isMetadataOnly,omitempty" tf:"is_metadata_only,omitempty"`

	// Describes the object's current state in detail. For example, it can be used to provide actionable information for a resource in a Failed state.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// Locks associated with this resource.
	Locks []DeploymentBackupLocksObservation `json:"locks,omitempty" tf:"locks,omitempty"`

	// Name of namespace that serves as a container for all of your buckets
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Name of the object to be uploaded to object storage
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// Version of OGG
	OggVersion *string `json:"oggVersion,omitempty" tf:"ogg_version,omitempty"`

	// The size of the backup stored in object storage (in bytes)
	SizeInBytes *float64 `json:"sizeInBytes,omitempty" tf:"size_in_bytes,omitempty"`

	// Possible lifecycle states.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The system tags associated with this resource, if any. The system tags are set by Oracle Cloud Infrastructure services. Each key is predefined and scoped to namespaces.  For more information, see Resource Tags.  Example: {orcl-cloud: {free-tier-retain: true}}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The time of the resource backup finish. The format is defined by RFC3339, such as 2016-08-25T21:10:29.600Z.
	TimeBackupFinished *string `json:"timeBackupFinished,omitempty" tf:"time_backup_finished,omitempty"`

	// When the lock was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The time of the resource backup. The format is defined by RFC3339, such as 2016-08-25T21:10:29.600Z.
	TimeOfBackup *string `json:"timeOfBackup,omitempty" tf:"time_of_backup,omitempty"`

	// The time the resource was last updated. The format is defined by RFC3339, such as 2016-08-25T21:10:29.600Z.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type DeploymentBackupParameters struct {

	// Name of the bucket where the object is to be uploaded in the object storage
	// +kubebuilder:validation:Optional
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Updatable) The OCID of the compartment being referenced.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Tags defined for this resource. Each key is predefined and scoped to a namespace.  Example: {"foo-namespace.bar-key": "value"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// The OCID of the deployment being referenced.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/goldengate/v1alpha1.Deployment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DeploymentID *string `json:"deploymentId,omitempty" tf:"deployment_id,omitempty"`

	// Reference to a Deployment in goldengate to populate deploymentId.
	// +kubebuilder:validation:Optional
	DeploymentIDRef *v1.Reference `json:"deploymentIdRef,omitempty" tf:"-"`

	// Selector for a Deployment in goldengate to populate deploymentId.
	// +kubebuilder:validation:Optional
	DeploymentIDSelector *v1.Selector `json:"deploymentIdSelector,omitempty" tf:"-"`

	// An object's Display Name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) A simple key-value pair that is applied without any predefined name, type, or scope. Exists for cross-compatibility only.  Example: {"bar-key": "value"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// +kubebuilder:validation:Optional
	IsLockOverride *bool `json:"isLockOverride,omitempty" tf:"is_lock_override,omitempty"`

	// Parameter to allow users to create backup without trails
	// +kubebuilder:validation:Optional
	IsMetadataOnly *bool `json:"isMetadataOnly,omitempty" tf:"is_metadata_only,omitempty"`

	// Locks associated with this resource.
	// +kubebuilder:validation:Optional
	Locks []DeploymentBackupLocksParameters `json:"locks,omitempty" tf:"locks,omitempty"`

	// Name of namespace that serves as a container for all of your buckets
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Name of the object to be uploaded to object storage
	// +kubebuilder:validation:Optional
	Object *string `json:"object,omitempty" tf:"object,omitempty"`
}

// DeploymentBackupSpec defines the desired state of DeploymentBackup
type DeploymentBackupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DeploymentBackupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DeploymentBackupInitParameters `json:"initProvider,omitempty"`
}

// DeploymentBackupStatus defines the observed state of DeploymentBackup.
type DeploymentBackupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DeploymentBackupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DeploymentBackup is the Schema for the DeploymentBackups API. Provides the Deployment Backup resource in Oracle Cloud Infrastructure Golden Gate service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type DeploymentBackup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.bucket) || (has(self.initProvider) && has(self.initProvider.bucket))",message="spec.forProvider.bucket is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.__namespace__) || (has(self.initProvider) && has(self.initProvider.__namespace__))",message="spec.forProvider.namespace is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.object) || (has(self.initProvider) && has(self.initProvider.object))",message="spec.forProvider.object is a required parameter"
	Spec   DeploymentBackupSpec   `json:"spec"`
	Status DeploymentBackupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DeploymentBackupList contains a list of DeploymentBackups
type DeploymentBackupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DeploymentBackup `json:"items"`
}

// Repository type metadata.
var (
	DeploymentBackup_Kind             = "DeploymentBackup"
	DeploymentBackup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DeploymentBackup_Kind}.String()
	DeploymentBackup_KindAPIVersion   = DeploymentBackup_Kind + "." + CRDGroupVersion.String()
	DeploymentBackup_GroupVersionKind = CRDGroupVersion.WithKind(DeploymentBackup_Kind)
)

func init() {
	SchemeBuilder.Register(&DeploymentBackup{}, &DeploymentBackupList{})
}
