/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DrPlanInitParameters struct {

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The display name of the DR plan being created.  Example: EBS Switchover PHX to IAD
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The OCID of the DR protection group to which this DR plan belongs.  Example: ocid1.drprotectiongroup.oc1..uniqueID
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/disasterrecovery/v1alpha1.DrProtectionGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DrProtectionGroupID *string `json:"drProtectionGroupId,omitempty" tf:"dr_protection_group_id,omitempty"`

	// Reference to a DrProtectionGroup in disasterrecovery to populate drProtectionGroupId.
	// +kubebuilder:validation:Optional
	DrProtectionGroupIDRef *v1.Reference `json:"drProtectionGroupIdRef,omitempty" tf:"-"`

	// Selector for a DrProtectionGroup in disasterrecovery to populate drProtectionGroupId.
	// +kubebuilder:validation:Optional
	DrProtectionGroupIDSelector *v1.Selector `json:"drProtectionGroupIdSelector,omitempty" tf:"-"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) An optional property when incremented triggers Refresh. Could be set to any integer value.
	RefreshTrigger *float64 `json:"refreshTrigger,omitempty" tf:"refresh_trigger,omitempty"`

	// The OCID of the source DR plan that should be cloned.  Example: ocid1.drplan.oc1..uniqueID
	SourcePlanID *string `json:"sourcePlanId,omitempty" tf:"source_plan_id,omitempty"`

	// The type of DR plan to be created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) An optional property when incremented triggers Verify. Could be set to any integer value.
	VerifyTrigger *float64 `json:"verifyTrigger,omitempty" tf:"verify_trigger,omitempty"`
}

type DrPlanObservation struct {

	// The OCID of the compartment containing the DR plan.  Example: ocid1.compartment.oc1..uniqueID
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The display name of the DR plan being created.  Example: EBS Switchover PHX to IAD
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The OCID of the DR protection group to which this DR plan belongs.  Example: ocid1.drprotectiongroup.oc1..uniqueID
	DrProtectionGroupID *string `json:"drProtectionGroupId,omitempty" tf:"dr_protection_group_id,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the DR plan.  Example: ocid1.drplan.oc1..uniqueID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A message describing the DR plan's current state in more detail.
	LifeCycleDetails *string `json:"lifeCycleDetails,omitempty" tf:"life_cycle_details,omitempty"`

	// The current state of the DR plan.
	LifecycleSubState *string `json:"lifecycleSubState,omitempty" tf:"lifecycle_sub_state,omitempty"`

	// The OCID of the peer DR protection group associated with this plan's DR protection group.  Example: ocid1.drprotectiongroup.oc1..uniqueID
	PeerDrProtectionGroupID *string `json:"peerDrProtectionGroupId,omitempty" tf:"peer_dr_protection_group_id,omitempty"`

	// The region of the peer DR protection group associated with this plan's DR protection group.  Example: us-ashburn-1
	PeerRegion *string `json:"peerRegion,omitempty" tf:"peer_region,omitempty"`

	// The list of groups in this DR plan.
	PlanGroups []PlanGroupsObservation `json:"planGroups,omitempty" tf:"plan_groups,omitempty"`

	// (Updatable) An optional property when incremented triggers Refresh. Could be set to any integer value.
	RefreshTrigger *float64 `json:"refreshTrigger,omitempty" tf:"refresh_trigger,omitempty"`

	// The OCID of the source DR plan that should be cloned.  Example: ocid1.drplan.oc1..uniqueID
	SourcePlanID *string `json:"sourcePlanId,omitempty" tf:"source_plan_id,omitempty"`

	// The current state of the DR plan.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Usage of system tag keys. These predefined keys are scoped to namespaces.  Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The date and time the DR plan was created. An RFC3339 formatted datetime string.  Example: 2019-03-29T09:36:42Z
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The date and time the DR plan was updated. An RFC3339 formatted datetime string.  Example: 2019-03-29T09:36:42Z
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// The type of DR plan to be created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) An optional property when incremented triggers Verify. Could be set to any integer value.
	VerifyTrigger *float64 `json:"verifyTrigger,omitempty" tf:"verify_trigger,omitempty"`
}

type DrPlanParameters struct {

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace.  Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The display name of the DR plan being created.  Example: EBS Switchover PHX to IAD
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The OCID of the DR protection group to which this DR plan belongs.  Example: ocid1.drprotectiongroup.oc1..uniqueID
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/disasterrecovery/v1alpha1.DrProtectionGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DrProtectionGroupID *string `json:"drProtectionGroupId,omitempty" tf:"dr_protection_group_id,omitempty"`

	// Reference to a DrProtectionGroup in disasterrecovery to populate drProtectionGroupId.
	// +kubebuilder:validation:Optional
	DrProtectionGroupIDRef *v1.Reference `json:"drProtectionGroupIdRef,omitempty" tf:"-"`

	// Selector for a DrProtectionGroup in disasterrecovery to populate drProtectionGroupId.
	// +kubebuilder:validation:Optional
	DrProtectionGroupIDSelector *v1.Selector `json:"drProtectionGroupIdSelector,omitempty" tf:"-"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) An optional property when incremented triggers Refresh. Could be set to any integer value.
	// +kubebuilder:validation:Optional
	RefreshTrigger *float64 `json:"refreshTrigger,omitempty" tf:"refresh_trigger,omitempty"`

	// The OCID of the source DR plan that should be cloned.  Example: ocid1.drplan.oc1..uniqueID
	// +kubebuilder:validation:Optional
	SourcePlanID *string `json:"sourcePlanId,omitempty" tf:"source_plan_id,omitempty"`

	// The type of DR plan to be created.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) An optional property when incremented triggers Verify. Could be set to any integer value.
	// +kubebuilder:validation:Optional
	VerifyTrigger *float64 `json:"verifyTrigger,omitempty" tf:"verify_trigger,omitempty"`
}

type ObjectStorageScriptLocationInitParameters struct {
}

type ObjectStorageScriptLocationObservation struct {

	// The bucket name inside the object storage namespace.  Example: custom_dr_scripts
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// The namespace in object storage (Note - this is usually the tenancy name).  Example: myocitenancy
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// The object name inside the object storage bucket.  Example: validate_app_start.sh
	Object *string `json:"object,omitempty" tf:"object,omitempty"`
}

type ObjectStorageScriptLocationParameters struct {
}

type PlanGroupsInitParameters struct {
}

type PlanGroupsObservation struct {

	// (Updatable) The display name of the DR plan being created.  Example: EBS Switchover PHX to IAD
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The OCID of the DR plan.  Example: ocid1.drplan.oc1..uniqueID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A flag indicating whether this group should be enabled for execution. This flag is only applicable to the USER_DEFINED_PAUSE group. The flag should be null for the remaining group types.  Example: true
	IsPauseEnabled *bool `json:"isPauseEnabled,omitempty" tf:"is_pause_enabled,omitempty"`

	// The DR plan group refresh status.  Example: GROUP_MODIFIED
	RefreshStatus *string `json:"refreshStatus,omitempty" tf:"refresh_status,omitempty"`

	// The list of steps in the group.
	Steps []StepsObservation `json:"steps,omitempty" tf:"steps,omitempty"`

	// The type of DR plan to be created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type PlanGroupsParameters struct {
}

type StepsInitParameters struct {
}

type StepsObservation struct {

	// (Updatable) The display name of the DR plan being created.  Example: EBS Switchover PHX to IAD
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The error mode for this step.
	ErrorMode *string `json:"errorMode,omitempty" tf:"error_mode,omitempty"`

	// The unique id of the group to which this step belongs. Must not be modified by user.  Example: sgid1.group..uniqueID
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// The OCID of the DR plan.  Example: ocid1.drplan.oc1..uniqueID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A flag indicating whether this step should be enabled for execution.  Example: true
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`

	// The OCID of the member associated with this step.  Example: ocid1.database.oc1..uniqueID
	MemberID *string `json:"memberId,omitempty" tf:"member_id,omitempty"`

	// The DR plan group refresh status.  Example: GROUP_MODIFIED
	RefreshStatus *string `json:"refreshStatus,omitempty" tf:"refresh_status,omitempty"`

	// The timeout in seconds for executing this step.  Example: 600
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// The type of DR plan to be created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The display name of the DR Plan step type.  Example: Database Switchover
	TypeDisplayName *string `json:"typeDisplayName,omitempty" tf:"type_display_name,omitempty"`

	// The details for a user-defined step in a DR plan.
	UserDefinedStep []UserDefinedStepObservation `json:"userDefinedStep,omitempty" tf:"user_defined_step,omitempty"`
}

type StepsParameters struct {
}

type UserDefinedStepInitParameters struct {
}

type UserDefinedStepObservation struct {

	// The OCID of function to be invoked.  Example: ocid1.fnfunc.oc1..uniqueID
	FunctionID *string `json:"functionId,omitempty" tf:"function_id,omitempty"`

	// The region in which the function is deployed.  Example: us-ashburn-1
	FunctionRegion *string `json:"functionRegion,omitempty" tf:"function_region,omitempty"`

	// The details of an object storage script location for a user-defined step in a DR plan.
	ObjectStorageScriptLocation []ObjectStorageScriptLocationObservation `json:"objectStorageScriptLocation,omitempty" tf:"object_storage_script_location,omitempty"`

	// The request body for the function.  Example: { "FnParam1", "FnParam2" }
	RequestBody *string `json:"requestBody,omitempty" tf:"request_body,omitempty"`

	// The userid on the instance to be used for executing the script or command.  Example: opc
	RunAsUser *string `json:"runAsUser,omitempty" tf:"run_as_user,omitempty"`

	// The OCID of the instance on which this script or command should be executed.
	RunOnInstanceID *string `json:"runOnInstanceId,omitempty" tf:"run_on_instance_id,omitempty"`

	// The region of the instance where this script or command should be executed.  Example: us-ashburn-1
	RunOnInstanceRegion *string `json:"runOnInstanceRegion,omitempty" tf:"run_on_instance_region,omitempty"`

	// The script name and arguments.  Example: /usr/bin/python3 /home/opc/scripts/my_app_script.py arg1 arg2 arg3
	ScriptCommand *string `json:"scriptCommand,omitempty" tf:"script_command,omitempty"`

	// The type of the user-defined step.
	StepType *string `json:"stepType,omitempty" tf:"step_type,omitempty"`
}

type UserDefinedStepParameters struct {
}

// DrPlanSpec defines the desired state of DrPlan
type DrPlanSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DrPlanParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DrPlanInitParameters `json:"initProvider,omitempty"`
}

// DrPlanStatus defines the observed state of DrPlan.
type DrPlanStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DrPlanObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DrPlan is the Schema for the DrPlans API. Provides the Dr Plan resource in Oracle Cloud Infrastructure Disaster Recovery service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type DrPlan struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   DrPlanSpec   `json:"spec"`
	Status DrPlanStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DrPlanList contains a list of DrPlans
type DrPlanList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DrPlan `json:"items"`
}

// Repository type metadata.
var (
	DrPlan_Kind             = "DrPlan"
	DrPlan_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DrPlan_Kind}.String()
	DrPlan_KindAPIVersion   = DrPlan_Kind + "." + CRDGroupVersion.String()
	DrPlan_GroupVersionKind = CRDGroupVersion.WithKind(DrPlan_Kind)
)

func init() {
	SchemeBuilder.Register(&DrPlan{}, &DrPlanList{})
}
