apiVersion: osmanagement.oci.upbound.io/v1alpha1
kind: ManagementHubManagedInstanceGroupInstallWindowsUpdatesManagement
metadata:
  annotations:
    meta.upbound.io/example-id: osmanagement/v1alpha1/managementhubmanagedinstancegroupinstallwindowsupdatesmanagement
  labels:
    testing.upbound.io/example-name: test_managed_instance_group_install_windows_updates_management
  name: test-managed-instance-group-install-windows-updates-management
spec:
  forProvider:
    managedInstanceGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_managed_instance_group
    windowsUpdateTypes: ${var.managed_instance_group_install_windows_updates_management_windows_update_types}
    workRequestDetails:
    - description: ${var.managed_instance_group_install_windows_updates_management_work_request_details_description}
      displayName: ${var.managed_instance_group_install_windows_updates_management_work_request_details_display_name}
