apiVersion: osmanagement.oci.upbound.io/v1alpha1
kind: ManagementHubProfileAttachManagedInstanceGroupManagement
metadata:
  annotations:
    meta.upbound.io/example-id: osmanagement/v1alpha1/managementhubprofileattachmanagedinstancegroupmanagement
  labels:
    testing.upbound.io/example-name: test_profile_attach_managed_instance_group_management
  name: test-profile-attach-managed-instance-group-management
spec:
  forProvider:
    managedInstanceGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_managed_instance_group
    profileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_profile
