apiVersion: osmanagement.oci.upbound.io/v1alpha1
kind: ManagementHubManagedInstanceAttachProfileManagement
metadata:
  annotations:
    meta.upbound.io/example-id: osmanagement/v1alpha1/managementhubmanagedinstanceattachprofilemanagement
  labels:
    testing.upbound.io/example-name: test_managed_instance_attach_profile_management
  name: test-managed-instance-attach-profile-management
spec:
  forProvider:
    managedInstanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_managed_instance
    profileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_profile
