apiVersion: osmanagement.oci.upbound.io/v1alpha1
kind: ManagementHubProfileAttachLifecycleStageManagement
metadata:
  annotations:
    meta.upbound.io/example-id: osmanagement/v1alpha1/managementhubprofileattachlifecyclestagemanagement
  labels:
    testing.upbound.io/example-name: test_profile_attach_lifecycle_stage_management
  name: test-profile-attach-lifecycle-stage-management
spec:
  forProvider:
    lifecycleStageId: ${oci_os_management_hub_lifecycle_stage.test_lifecycle_stage.id}
    profileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_profile
