apiVersion: osmanagement.oci.upbound.io/v1alpha1
kind: ManagementHubSoftwareSourceChangeAvailabilityManagement
metadata:
  annotations:
    meta.upbound.io/example-id: osmanagement/v1alpha1/managementhubsoftwaresourcechangeavailabilitymanagement
  labels:
    testing.upbound.io/example-name: test_software_source_change_availability_management
  name: test-software-source-change-availability-management
spec:
  forProvider:
    softwareSourceAvailabilities:
    - availability: ${var.software_source_change_availability_management_software_source_availabilities_availability}
      availabilityAtOci: ${var.software_source_change_availability_management_software_source_availabilities_availability_at_oci}
      softwareSourceIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_software_source
