/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type SoftwareSourceManifestInitParameters struct {

	// (Updatable) Provides the manifest content used to update the package list of the software source.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// The OCID of the software source.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/osmanagementhub/v1alpha1.SoftwareSource
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	SoftwareSourceID *string `json:"softwareSourceId,omitempty" tf:"software_source_id,omitempty"`

	// Reference to a SoftwareSource in osmanagementhub to populate softwareSourceId.
	// +kubebuilder:validation:Optional
	SoftwareSourceIDRef *v1.Reference `json:"softwareSourceIdRef,omitempty" tf:"-"`

	// Selector for a SoftwareSource in osmanagementhub to populate softwareSourceId.
	// +kubebuilder:validation:Optional
	SoftwareSourceIDSelector *v1.Selector `json:"softwareSourceIdSelector,omitempty" tf:"-"`
}

type SoftwareSourceManifestObservation struct {

	// (Updatable) Provides the manifest content used to update the package list of the software source.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the software source.
	SoftwareSourceID *string `json:"softwareSourceId,omitempty" tf:"software_source_id,omitempty"`
}

type SoftwareSourceManifestParameters struct {

	// (Updatable) Provides the manifest content used to update the package list of the software source.
	// +kubebuilder:validation:Optional
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// The OCID of the software source.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/osmanagementhub/v1alpha1.SoftwareSource
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	SoftwareSourceID *string `json:"softwareSourceId,omitempty" tf:"software_source_id,omitempty"`

	// Reference to a SoftwareSource in osmanagementhub to populate softwareSourceId.
	// +kubebuilder:validation:Optional
	SoftwareSourceIDRef *v1.Reference `json:"softwareSourceIdRef,omitempty" tf:"-"`

	// Selector for a SoftwareSource in osmanagementhub to populate softwareSourceId.
	// +kubebuilder:validation:Optional
	SoftwareSourceIDSelector *v1.Selector `json:"softwareSourceIdSelector,omitempty" tf:"-"`
}

// SoftwareSourceManifestSpec defines the desired state of SoftwareSourceManifest
type SoftwareSourceManifestSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SoftwareSourceManifestParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SoftwareSourceManifestInitParameters `json:"initProvider,omitempty"`
}

// SoftwareSourceManifestStatus defines the observed state of SoftwareSourceManifest.
type SoftwareSourceManifestStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SoftwareSourceManifestObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SoftwareSourceManifest is the Schema for the SoftwareSourceManifests API. Provides the Software Source Manifest resource in Oracle Cloud Infrastructure Os Management Hub service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type SoftwareSourceManifest struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SoftwareSourceManifestSpec   `json:"spec"`
	Status            SoftwareSourceManifestStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SoftwareSourceManifestList contains a list of SoftwareSourceManifests
type SoftwareSourceManifestList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SoftwareSourceManifest `json:"items"`
}

// Repository type metadata.
var (
	SoftwareSourceManifest_Kind             = "SoftwareSourceManifest"
	SoftwareSourceManifest_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SoftwareSourceManifest_Kind}.String()
	SoftwareSourceManifest_KindAPIVersion   = SoftwareSourceManifest_Kind + "." + CRDGroupVersion.String()
	SoftwareSourceManifest_GroupVersionKind = CRDGroupVersion.WithKind(SoftwareSourceManifest_Kind)
)

func init() {
	SchemeBuilder.Register(&SoftwareSourceManifest{}, &SoftwareSourceManifestList{})
}
