apiVersion: vault.oci.upbound.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: vault/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: test_secret
  name: test-secret
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    keyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    secretContent:
    - content: PHZhcj4mbHQ7YmFzZTY0X2VuY29kZWRfc2VjcmV0X2NvbnRlbnRzJmd0OzwvdmFyPg==
      contentType: BASE64
      name: name
      stage: CURRENT
    secretName: testSecretSample1
    vaultIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
