apiVersion: blockstorage.oci.upbound.io/v1alpha1
kind: BootVolume
metadata:
  annotations:
    meta.upbound.io/example-id: blockstorage/v1alpha1/bootvolume
  labels:
    testing.upbound.io/example-name: test_boot_volume_from_source_boot_volume
  name: test-boot-volume-from-source-boot-volume
spec:
  forProvider:
    availabilityDomain: ${oci_core_instance.test_instance.availability_domain}
    compartmentId: ${oci_core_instance.test_instance.compartment_id}
    sourceDetails:
    - id: ${oci_core_instance.test_instance.boot_volume_id}
      type: bootVolume

---

apiVersion: compute.oci.upbound.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: blockstorage/v1alpha1/bootvolume
  labels:
    testing.upbound.io/example-name: test_instance
  name: test-instance
spec:
  forProvider:
    availabilityDomain: ${data.oci_identity_availability_domain.ad.name}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    createVnicDetails:
    - assignPublicIp: true
      displayName: Primaryvnic
      hostnameLabel: testinstance
      subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_subnet
    displayName: TestInstance
    shape: VM.Standard2.1
    sourceDetails:
    - sourceIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      sourceType: image
    timeouts:
    - create: 60m

---

apiVersion: networking.oci.upbound.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: blockstorage/v1alpha1/bootvolume
  labels:
    testing.upbound.io/example-name: test_subnet
  name: test-subnet
spec:
  forProvider:
    availabilityDomain: ${data.oci_identity_availability_domain.ad.name}
    cidrBlock: 10.1.20.0/24
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    dhcpOptionsIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_vcn
    displayName: TestSubnet
    dnsLabel: testsubnet
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_vcn
    securityListIdRefs:
    - name: test_vcn
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_vcn

---

apiVersion: networking.oci.upbound.io/v1alpha1
kind: Vcn
metadata:
  annotations:
    meta.upbound.io/example-id: blockstorage/v1alpha1/bootvolume
  labels:
    testing.upbound.io/example-name: test_vcn
  name: test-vcn
spec:
  forProvider:
    cidrBlock: 10.1.0.0/16
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    displayName: TestVcn
    dnsLabel: testvcn
