/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ClusterCompleteCredentialRotationManagementInitParameters struct {

	// The OCID of the cluster.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/containerengine/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in containerengine to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in containerengine to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`
}

type ClusterCompleteCredentialRotationManagementObservation struct {

	// The OCID of the cluster.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ClusterCompleteCredentialRotationManagementParameters struct {

	// The OCID of the cluster.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/containerengine/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in containerengine to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in containerengine to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`
}

// ClusterCompleteCredentialRotationManagementSpec defines the desired state of ClusterCompleteCredentialRotationManagement
type ClusterCompleteCredentialRotationManagementSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ClusterCompleteCredentialRotationManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterCompleteCredentialRotationManagementInitParameters `json:"initProvider,omitempty"`
}

// ClusterCompleteCredentialRotationManagementStatus defines the observed state of ClusterCompleteCredentialRotationManagement.
type ClusterCompleteCredentialRotationManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClusterCompleteCredentialRotationManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClusterCompleteCredentialRotationManagement is the Schema for the ClusterCompleteCredentialRotationManagements API. Provides the Cluster Complete Credential Rotation Management resource in Oracle Cloud Infrastructure Container Engine service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type ClusterCompleteCredentialRotationManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ClusterCompleteCredentialRotationManagementSpec   `json:"spec"`
	Status            ClusterCompleteCredentialRotationManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterCompleteCredentialRotationManagementList contains a list of ClusterCompleteCredentialRotationManagements
type ClusterCompleteCredentialRotationManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterCompleteCredentialRotationManagement `json:"items"`
}

// Repository type metadata.
var (
	ClusterCompleteCredentialRotationManagement_Kind             = "ClusterCompleteCredentialRotationManagement"
	ClusterCompleteCredentialRotationManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClusterCompleteCredentialRotationManagement_Kind}.String()
	ClusterCompleteCredentialRotationManagement_KindAPIVersion   = ClusterCompleteCredentialRotationManagement_Kind + "." + CRDGroupVersion.String()
	ClusterCompleteCredentialRotationManagement_GroupVersionKind = CRDGroupVersion.WithKind(ClusterCompleteCredentialRotationManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&ClusterCompleteCredentialRotationManagement{}, &ClusterCompleteCredentialRotationManagementList{})
}
