/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Cluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Datastore) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DatastoreCluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EsxiHost) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Sddc) Hub() {}
