/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type IotDomainChangeDataRetentionPeriodInitParameters struct {

	// The duration (in days) for which data will be retained in the IoT domain.
	DataRetentionPeriodInDays *float64 `json:"dataRetentionPeriodInDays,omitempty" tf:"data_retention_period_in_days,omitempty"`

	// The OCID of the IoT domain.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/iot/v1alpha1.IotDomain
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	IotDomainID *string `json:"iotDomainId,omitempty" tf:"iot_domain_id,omitempty"`

	// Reference to a IotDomain in iot to populate iotDomainId.
	// +kubebuilder:validation:Optional
	IotDomainIDRef *v1.Reference `json:"iotDomainIdRef,omitempty" tf:"-"`

	// Selector for a IotDomain in iot to populate iotDomainId.
	// +kubebuilder:validation:Optional
	IotDomainIDSelector *v1.Selector `json:"iotDomainIdSelector,omitempty" tf:"-"`

	// The type of data retention period to apply. Allowed values are RAW_DATA, REJECTED_DATA, HISTORIZED_DATA, and RAW_COMMAND_DATA.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IotDomainChangeDataRetentionPeriodObservation struct {

	// The duration (in days) for which data will be retained in the IoT domain.
	DataRetentionPeriodInDays *float64 `json:"dataRetentionPeriodInDays,omitempty" tf:"data_retention_period_in_days,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the IoT domain.
	IotDomainID *string `json:"iotDomainId,omitempty" tf:"iot_domain_id,omitempty"`

	// The type of data retention period to apply. Allowed values are RAW_DATA, REJECTED_DATA, HISTORIZED_DATA, and RAW_COMMAND_DATA.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IotDomainChangeDataRetentionPeriodParameters struct {

	// The duration (in days) for which data will be retained in the IoT domain.
	// +kubebuilder:validation:Optional
	DataRetentionPeriodInDays *float64 `json:"dataRetentionPeriodInDays,omitempty" tf:"data_retention_period_in_days,omitempty"`

	// The OCID of the IoT domain.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/iot/v1alpha1.IotDomain
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	IotDomainID *string `json:"iotDomainId,omitempty" tf:"iot_domain_id,omitempty"`

	// Reference to a IotDomain in iot to populate iotDomainId.
	// +kubebuilder:validation:Optional
	IotDomainIDRef *v1.Reference `json:"iotDomainIdRef,omitempty" tf:"-"`

	// Selector for a IotDomain in iot to populate iotDomainId.
	// +kubebuilder:validation:Optional
	IotDomainIDSelector *v1.Selector `json:"iotDomainIdSelector,omitempty" tf:"-"`

	// The type of data retention period to apply. Allowed values are RAW_DATA, REJECTED_DATA, HISTORIZED_DATA, and RAW_COMMAND_DATA.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// IotDomainChangeDataRetentionPeriodSpec defines the desired state of IotDomainChangeDataRetentionPeriod
type IotDomainChangeDataRetentionPeriodSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IotDomainChangeDataRetentionPeriodParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IotDomainChangeDataRetentionPeriodInitParameters `json:"initProvider,omitempty"`
}

// IotDomainChangeDataRetentionPeriodStatus defines the observed state of IotDomainChangeDataRetentionPeriod.
type IotDomainChangeDataRetentionPeriodStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IotDomainChangeDataRetentionPeriodObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IotDomainChangeDataRetentionPeriod is the Schema for the IotDomainChangeDataRetentionPeriods API. Provides the Iot Domain Change Data Retention Period resource in Oracle Cloud Infrastructure Iot service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type IotDomainChangeDataRetentionPeriod struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dataRetentionPeriodInDays) || (has(self.initProvider) && has(self.initProvider.dataRetentionPeriodInDays))",message="spec.forProvider.dataRetentionPeriodInDays is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   IotDomainChangeDataRetentionPeriodSpec   `json:"spec"`
	Status IotDomainChangeDataRetentionPeriodStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IotDomainChangeDataRetentionPeriodList contains a list of IotDomainChangeDataRetentionPeriods
type IotDomainChangeDataRetentionPeriodList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IotDomainChangeDataRetentionPeriod `json:"items"`
}

// Repository type metadata.
var (
	IotDomainChangeDataRetentionPeriod_Kind             = "IotDomainChangeDataRetentionPeriod"
	IotDomainChangeDataRetentionPeriod_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IotDomainChangeDataRetentionPeriod_Kind}.String()
	IotDomainChangeDataRetentionPeriod_KindAPIVersion   = IotDomainChangeDataRetentionPeriod_Kind + "." + CRDGroupVersion.String()
	IotDomainChangeDataRetentionPeriod_GroupVersionKind = CRDGroupVersion.WithKind(IotDomainChangeDataRetentionPeriod_Kind)
)

func init() {
	SchemeBuilder.Register(&IotDomainChangeDataRetentionPeriod{}, &IotDomainChangeDataRetentionPeriodList{})
}
